// Generated by scripts/pack-characters.mjs
export const CHARACTER_ASSETS={
  "models": {
    "silver-outfit": {
      "file": "silver-outfit-f2be672751e9.glb.gz",
      "bytes": 657965
    },
    "scout-outfit": {
      "file": "scout-outfit-6fb52a619af8.glb.gz",
      "bytes": 587773
    },
    "silver-base": {
      "file": "silver-base-48dad48ef811.glb.gz",
      "bytes": 328225
    },
    "scout-base": {
      "file": "scout-base-f5733a01d0f9.glb.gz",
      "bytes": 319394
    },
    "silver-hair": {
      "file": "silver-hair-82630a338a36.glb.gz",
      "bytes": 79917
    },
    "scout-hair": {
      "file": "scout-hair-818c31a15ae2.glb.gz",
      "bytes": 35716
    }
  },
  "textures": [
    "texture-dd64da2af318.webp",
    "texture-846ef2170b04.webp",
    "texture-aca03d2fba12.webp",
    "texture-e1051d3d56df.webp",
    "texture-3b6ab973f9f3.webp",
    "texture-da541fbd4b3b.webp",
    "texture-10cd71e2453e.webp",
    "texture-b4dcc0f4139a.webp",
    "texture-086c2eb25bdd.webp",
    "texture-172f230aae0d.webp",
    "texture-f9f4f2fb3eee.webp",
    "texture-9ed61f7726a5.webp",
    "texture-d08e3356a832.webp",
    "texture-cf922460b43c.webp",
    "texture-743f811857db.webp",
    "texture-d2beabf2bd03.webp",
    "texture-57fd0ad8c96a.webp",
    "texture-bc7aa863bd22.webp",
    "texture-9b25cf920021.webp",
    "texture-419f96dbb881.webp",
    "texture-c70dabf48574.webp"
  ],
  "motion": {
    "file": "motion-c8b2ca84695c.json.gz",
    "bytes": 412394
  },
  "motionFallback": {
    "file": "motion-5d714a26718b.json",
    "bytes": 1595534
  }
};
