import{SCOUT_ROLL_DURATION,rollTravel}from'./dodge-motion.js?v=24';
import{renderPixelRatio,RenderBudget}from'./render-budget.js?v=21';
import{groundCue,disposeCue}from'./ground-cues.js?v=19';
import{SkillVFX}from'./skill-vfx.js?v=22';
import{loadHeroAssets,disposeHero}from'./skinned-hero.js?v=24';
import{GameAudio}from'./audio.js?v=18';
import{ENEMY_GUIDE,CIRCLE_GUIDE}from'./battle-guide.js?v=19';
import * as T from './vendor/three.module.js';
import{MAPS,WEAPONS,ENEMIES,weaponFor,experienceNeeded,grantExperience,chooseUpgrades,takeUpgrade,weaponStats,WEAPON_PATHS,segmentDistance,registerCrossbowHit,registerShadowHit}from'./rules.js?v=18';
import{actor,animateActor,animateWorld,buildWorld,clearAt,moveActor,mesh,mat}from'./world.js?v=24';
const $=s=>document.querySelector(s),touch=matchMedia('(pointer:coarse)').matches;
document.body.classList.toggle('touch',touch);
const canvas=$('#world');let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('#error').hidden=false;$('#error').textContent='无法启动 3D 画面。请使用支持 WebGL 的较新浏览器，并开启硬件加速。';throw e;}
const renderBudget=new RenderBudget();let renderWidth=0,renderHeight=0,renderDpr=0,shadowClock=0,skillsHTML=null;
renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,180);scene.add(new T.HemisphereLight(0xc8f5ed,0x273c39,2.8));
const vfx=new SkillVFX(scene,{mobile:touch});
const sun=new T.DirectionalLight(0xffe3b3,3.2);sun.position.set(15,30,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-28,right:28,top:28,bottom:-28,near:.5,far:80});sun.shadow.bias=-.001;sun.shadow.normalBias=.012;scene.add(sun,sun.target);
const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=64;const glowCtx=glowCanvas.getContext('2d'),gradient=glowCtx.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'rgba(255,255,255,.8)');gradient.addColorStop(.3,'rgba(255,255,255,.35)');gradient.addColorStop(1,'rgba(255,255,255,0)');glowCtx.fillStyle=gradient;glowCtx.fillRect(0,0,64,64);const glowTexture=new T.CanvasTexture(glowCanvas),glowMaterials=new Map();
function glow(color,size){if(!glowMaterials.has(color))glowMaterials.set(color,new T.SpriteMaterial({map:glowTexture,color,transparent:true,opacity:.6,depthWrite:false,blending:T.AdditiveBlending}));const s=new T.Sprite(glowMaterials.get(color));s.scale.set(size,size,1);return s;}
const rim=new T.DirectionalLight(0x93cfd9,1.3);rim.position.set(-10,10,-15);scene.add(rim);
let world,hero,heroId='silver',mapId='forest',weaponIndex=0,state='menu',time=0,kills=0,player,enemyId=0,enemies=[],bullets=[],orbs=[],effects=[],zones=[],fields=[],riftStrikes=[],spawnTimer=2,waveTimer=32,boss=null,bossBorn=false,toastTimer=0,shake=0,simTimer=0;
let attackMode='manual';try{if(localStorage.getItem('forest-echoes-attack-mode')==='auto')attackMode='auto';}catch{}
const keys=new Set(),stick={x:0,z:0,id:null},aimStick={id:null},aimInput={held:false,angle:0,hasAim:false},mouseAim={x:0,y:0,valid:false},aimRay=new T.Raycaster(),groundPlane=new T.Plane(new T.Vector3(0,1,0),0),camTarget=new T.Vector3(),temp=new T.Vector3();let last=performance.now(),uiTime=0;
const introduced=new Set(),introductions=[];let encounterTime=0;
const sound=new GameAudio();
function syncAudioUI(){const active=sound.ctx?.state==='running';$('#sound').textContent=sound.muted?'声音：关':active?'声音：开':'开启声音';$('#sound').setAttribute('aria-pressed',String(!sound.muted));$('#music-volume').value=Math.round(sound.musicVolume*100);$('#sfx-volume').value=Math.round(sound.sfxVolume*100);$('#music-value').textContent=Math.round(sound.musicVolume*100)+'%';$('#sfx-value').textContent=Math.round(sound.sfxVolume*100)+'%';}
async function unlockAudio(){const ok=await sound.init();syncAudioUI();if(!ok)toast('声音尚未开启，请点右上角“开启声音”重试');}
for(const bus of ['music','sfx'])$('#'+bus+'-volume').addEventListener('input',e=>{sound.setVolume(bus,Number(e.target.value)/100);unlockAudio();syncAudioUI();});
syncAudioUI();
function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;toastTimer=3;}
function showNextIntroduction(){const item=introductions.shift(),card=$('#encounter');if(!item){card.hidden=true;encounterTime=0;return;}card.querySelector('strong').textContent=item.title;card.querySelector('span').textContent=item.text;card.hidden=false;encounterTime=5;}
function introduce(key,title,text){if(introduced.has(key))return;introduced.add(key);introductions.push({title,text});if(!encounterTime)showNextIntroduction();}
function introduceEnemy(kind){const info=ENEMY_GUIDE[kind];if(info)introduce('enemy:'+kind,'新物种 · '+info.name,info.attack+'。'+info.tip);}
function introduceCircle(kind,title,text){introduce('circle:'+kind,title,text);}
function effect(kind,x,z,color,r=1,y=.15){if(effects.length>170)return;let m;if(kind==='cue'||kind==='target'){m=groundCue(color,r,kind==='target'?'pounce':'danger');m.position.set(x,y,z);}else if(kind==='spike')m=mesh('ConeGeometry',[.2,1.5,5],color,x,y,z,null,true);else m=mesh('SphereGeometry',[1,7,5],color,x,y,z,null,true);if(['spark','meteor'].includes(kind))m.add(glow(color,5));scene.add(m);effects.push({mesh:m,kind,life:kind==='cue'?.6:.55,max:kind==='cue'?.6:.55,r,vy:kind==='spark'?2.5:kind==='meteor'?-10:0,x,z});return m;}
function impactChips(x,z,color,count=2){for(let i=0;i<count;i++){if(effects.length>170)break;const a=Math.random()*Math.PI*2,m=mesh('SphereGeometry',[1,5,3],color,x,1,z,null,true),r=.035+Math.random()*.035;m.scale.setScalar(r);scene.add(m);effects.push({mesh:m,kind:'chip',life:.16,max:.16,r,vy:.6+Math.random(),vx:Math.sin(a)*1.8,vz:Math.cos(a)*1.8});}}
function burst(kind,x,z,r=2){if(kind==='heal')vfx.rise(x,z,0xbdf1a4,r);else if(kind==='ice')vfx.ice(x,z,r);else if(kind==='dark')vfx.dark(x,z,r);else if(kind==='hex')vfx.mist(x,z,r,0x83dcb3);else vfx.fire(x,z,r,true);sound.spell(kind==='hex'?'dark':kind);}
function lightning(ax,az,bx,bz,vertical=false){vfx.lightning(ax,az,bx,bz,vertical);sound.spell('storm');}
function clearObjects(){vfx.clear();fields=[];riftStrikes=[];for(const list of [enemies,bullets,orbs,effects,zones])for(const o of list){scene.remove(o.mesh);disposeCue(o.mesh);if(o.kind==='line'){o.mesh.geometry.dispose();o.mesh.material.dispose();}}if(boss)scene.remove(boss.mesh);enemies=[];bullets=[];orbs=[];effects=[];zones=[];boss=null;}
function build(){renderer.shadowMap.needsUpdate=true;renderBudget.reset();clearObjects();if(world){scene.remove(world.group);world.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();disposeCue(o);if(o.userData.ownedGeometry)o.geometry.dispose();});}if(hero){disposeHero(hero);scene.remove(hero);}world=buildWorld(mapId,Math.floor(Math.random()*1e8));scene.add(world.group);scene.background=new T.Color(world.theme.fog);scene.fog=new T.FogExp2(world.theme.fog,.014);hero=actor(heroId,weaponFor(heroId,weaponIndex).id);scene.add(hero);player={...world.spawn,heroId,weaponId:weaponFor(heroId,weaponIndex).id,weaponPath:null,hp:120,maxHp:120,level:1,xp:0,pending:0,upgrades:{},attack:0,dash:0,dashTime:0,inv:0,hurt:0,hexSlow:0,angle:0,spell:{fire:3,ice:3,storm:3,veil:3,chain:3,rift:3},distance:0};hero.position.set(player.x,0,player.z);camTarget.set(player.x,0,player.z);updateCamera(1);}
function renderChoices(){const box=$('#weapons');box.replaceChildren();for(let i=0;i<3;i++){const w=weaponFor(heroId,i),b=document.createElement('button');b.textContent=w.name;b.classList.toggle('selected',i===weaponIndex);b.onclick=()=>{weaponIndex=i;renderChoices();build();};box.append(b);}const selected=weaponFor(heroId,weaponIndex).id,identity={shade:'掌心发射影脉，三次命中引爆刻印。',shadowblade:'投出弧形影镰，飞回时可再次命中。',grimoire:'托举魔典，在瞄准方向的敌人脚下撕开延迟爆发的裂口。'};$('#weapon-preview').textContent=(identity[selected]||'')+'成长路线：'+Object.values(WEAPON_PATHS).filter(p=>p.weapon===selected).map(p=>p.name).join(' / ')+' · 3 级起二选一';$('.menu-caption span').textContent=heroId==='wraith'?'影裔 / SHADOW WRAITH':heroId==='silver'?'霜影 / SILVER VEIL':'游侠 / WOODLAND RANGER';}
function setAttackMode(mode){if(mode!=='manual'&&mode!=='auto')return;clearAttack();attackMode=mode;document.body.classList.toggle('auto-attack',mode==='auto');for(const button of document.querySelectorAll('[data-attack-mode]'))button.setAttribute('aria-pressed',String(button.dataset.attackMode===mode));$('#control-help').innerHTML=mode==='auto'?'靠近怪物后自动瞄准并攻击 · 电脑 WASD / 方向键移动，Shift 闪避<br>手机左摇杆移动、按钮闪避 · 建议横屏游玩':'电脑 WASD / 方向键移动 · 鼠标瞄准并按住左键攻击 · Shift 闪避<br>手机左摇杆移动、右摇杆拖动瞄准并射击 · 建议横屏游玩';try{localStorage.setItem('forest-echoes-attack-mode',mode);}catch{}}
for(const button of document.querySelectorAll('[data-attack-mode]'))button.onclick=()=>setAttackMode(button.dataset.attackMode);
for(const b of document.querySelectorAll('[data-hero]'))b.onclick=()=>{heroId=b.dataset.hero;weaponIndex=0;for(const q of document.querySelectorAll('[data-hero]'))q.classList.toggle('selected',q===b);renderChoices();build();};
for(const b of document.querySelectorAll('[data-map]'))b.onclick=()=>{mapId=b.dataset.map;for(const q of document.querySelectorAll('[data-map]'))q.classList.toggle('selected',q===b);build();};
function start(){unlockAudio();sound.reset(mapId);$('#audio-settings').open=false;keys.clear();releaseStick();clearAttack();introduced.clear();introductions.length=0;encounterTime=0;$('#encounter').hidden=true;build();time=0;kills=0;spawnTimer=1;waveTimer=32;bossBorn=false;state='playing';document.body.classList.add('playing');$('#menu').hidden=true;$('#hud').hidden=false;$('#touch').hidden=!touch;$('#dialog').close();$('#hero-name').textContent=heroId==='wraith'?'影裔':heroId==='silver'?'霜影':'林地游侠';toast('寻找补给与祭坛 · 3 分钟后迎战林心守卫');if(mapId==='ash')introduceCircle('vent','赤烬地脉','地面亮起橙红色地面预警后会喷发；人和怪物都要避开。');}
$('#start').onclick=start;
function dialog(title,body,buttons=[]){const content=$('#dialog-content');content.innerHTML='<h2>'+title+'</h2><p>'+body+'</p>';const actions=document.createElement('div');actions.className='dialog-actions';for(const [text,fn]of buttons){const b=document.createElement('button');b.textContent=text;b.onclick=fn;actions.append(b);}content.append(actions);if(!$('#dialog').open)$('#dialog').showModal();}
function showPauseDialog(){dialog('在林间歇一会儿','当前生命、技能与探索进度已保留。攻击方式：'+(attackMode==='auto'?'自动瞄准并攻击':'手动瞄准并攻击')+'。',[['继续远征',resume],[attackMode==='auto'?'切换为手动攻击':'切换为自动攻击',()=>{setAttackMode(attackMode==='auto'?'manual':'auto');showPauseDialog();}],['结束本局',()=>dialog('结束这次远征？','返回准备界面将结束当前对局。',[['返回暂停',()=>{state='playing';pause();}],['确认结束',menu]])]]);}
function pause(){if(state==='playing'){state='paused';keys.clear();releaseStick();clearAttack();showPauseDialog();}else if(state==='paused')resume();}
function resume(){state='playing';$('#dialog').close();keys.clear();releaseStick();clearAttack();unlockAudio();}
function menu(){state='menu';$('#dialog').close();$('#menu').hidden=false;$('#hud').hidden=true;$('#touch').hidden=true;$('#encounter').hidden=true;introductions.length=0;encounterTime=0;document.body.classList.remove('playing');keys.clear();releaseStick();clearAttack();build();}
$('#pause').onclick=pause;$('#dialog').addEventListener('cancel',e=>{e.preventDefault();if(state==='paused')resume();});
$('#battle-guide').onclick=()=>{const playing=state==='playing';if(!playing&&state!=='menu')return;if(playing){state='paused';keys.clear();releaseStick();clearAttack();}dialog('战场说明','新怪物首次出现时会弹出介绍。这里可以随时查攻击方式与地面提示的含义。',[[playing?'继续远征':'返回准备',playing?resume:()=>$('#dialog').close()]]);
 const panel=document.createElement('section');panel.className='guide-content';panel.innerHTML='<h3>怪物攻击 · 下滑查看更多</h3>'+Object.values(ENEMY_GUIDE).map(info=>`<p><strong>${info.name}</strong> · ${info.attack}<br><small>${info.tip}</small></p>`).join('')+'<h3>地面提示代表什么</h3>'+CIRCLE_GUIDE.map(info=>`<p><b>${info.color} · ${info.name}</b><br><small>${info.meaning}</small></p>`).join('');$('#dialog-content').insertBefore(panel,$('#dialog-content .dialog-actions'));};
$('#sound').onclick=()=>{if(sound.ctx?.state==='running')sound.setMuted(!sound.muted);else sound.setMuted(false);unlockAudio();syncAudioUI();};
function upgrade(){if(player.pending<=0||state!=='playing')return;state='upgrade';keys.clear();releaseStick();clearAttack();const choices=chooseUpgrades(player);if(!choices.length){player.pending=0;state='playing';return;}
 const path=WEAPON_PATHS[player.weaponPath?.id],weapon=weaponFor(heroId,weaponIndex);
 dialog('灵光汇聚 · 选择成长','Lv.'+player.level+' · '+weapon.name+(path?' / '+path.name+' '+player.weaponPath.rank+'阶':' · 3 级起可选专属路线'));
 const cards=document.createElement('div');cards.className='cards';for(const u of choices){const b=document.createElement('button'),weaponCard=u.category==='weapon',rank=weaponCard?u.rank:player.upgrades[u.id]||0;b.dataset.upgrade=u.id;b.className=weaponCard?'weapon-upgrade':'';
 b.innerHTML='<span class="upgrade-kind">'+(weaponCard?'武器路线 · '+(rank+1)+' 阶':['fire','ice','storm','veil','chain','rift'].includes(u.id)?'独立法术':'生存强化')+'</span><em>'+u.icon+'</em><strong>'+u.name+'</strong><small>'+u.text+'<br><span class="upgrade-rank">'+(weaponCard&&rank===0?'选定后锁定本路线':'当前 '+rank+' / '+u.max+(weaponCard?' · 继承已有路线效果':''))+'</span></small>';
 b.onclick=()=>{if(!takeUpgrade(player,u.id))return;player.pending--;state='playing';$('#dialog').close();sound.level();impactChips(player.x,player.z,0xbfffe7,4);if(player.pending)upgrade();};cards.append(b);}$('#dialog-content').append(cards);
 const note=document.createElement('p');note.className='upgrade-note';note.textContent=heroId==='wraith'?'武器路线在 3 / 5 / 8 级可进阶。暗幕、缚影、裂隙是独立暗影法术。':'武器路线在 3 / 5 / 8 级可进阶。火、冰、雷是独立法术，不会把火杖改成冰武器。';$('#dialog-content').append(note);
}
function finish(win){state=win?'won':'lost';keys.clear();releaseStick();clearAttack();dialog(win?'林心重归宁静':'这一程，暂告段落',`${MAPS[mapId].name} · 存活 ${Math.floor(time/60)} 分 ${Math.floor(time%60)} 秒<br>击败 ${kills} · 等级 ${player.level} · 探索 ${world.sites.filter(s=>s.claimed).length}/2`,[['再次远征',start],['选择角色与地图',menu]]);}
function hitPlayer(n,x,z){if(player.inv>0||state!=='playing')return;player.hp=Math.max(0,player.hp-n);player.inv=.7;player.hurt=.35;shake=.16;$('#damage-edge').style.opacity=.7;impactChips(player.x,player.z,0xf49c85,5);sound.hurt();if(player.hp<=0)finish(false);}
function spawn(kind,x=null,z=null,site=null){if(!site&&enemies.filter(e=>e.alive).length>=60)return null;if(x===null){for(let i=0;i<25;i++){const a=Math.random()*Math.PI*2,d=19+Math.random()*7;const nx=player.x+Math.cos(a)*d,nz=player.z+Math.sin(a)*d;if(clearAt(world,nx,nz,1)){x=nx;z=nz;break;}}}if(x===null||!clearAt(world,x,z,.65))return null;const cfg=ENEMIES[kind],e={...cfg,x,z,kind,id:++enemyId,alive:true,hp:cfg.hp*(1+Math.min(time,300)*.003),maxHp:cfg.hp*(1+Math.min(time,300)*.003),cool:1+Math.random(),wind:0,hurt:0,slow:0,site};e.mesh=actor(kind);e.mesh.position.set(x,0,z);scene.add(e.mesh);enemies.push(e);introduceEnemy(kind);return e;}
function hurtEnemy(e,n,flash=true){if(!e.alive)return;e.hp-=n*(e===boss&&e.recover>0?1.25:1);if(flash)e.hurt=.12;if(e.hp<=0){e.alive=false;if(e.marker){e.marker.mesh.visible=false;e.marker.life=0;e.marker=null;}kills++;scene.remove(e.mesh);impactChips(e.x,e.z,0xd9d5aa,4);if(e===boss){finish(true);return;}const o={x:e.x,z:e.z,mesh:mesh('OctahedronGeometry',[.22],0x76f0ef,e.x,.5,e.z,null,true),xp:e.xp};o.mesh.add(glow(0x61e6ed,2.2));scene.add(o.mesh);orbs.push(o);}}
function shoot(){const w=weaponStats(player),angle=aimInput.angle,targets=enemies.filter(e=>e.alive);if(boss?.alive)targets.push(boss);let nearest=null,d=w.range;
 if(w.id==='dark'&&player.weaponPath?.id==='dark_seek')for(const e of targets){const n=Math.hypot(e.x-player.x,e.z-player.z),direction=Math.atan2(e.x-player.x,e.z-player.z),diff=Math.atan2(Math.sin(direction-angle),Math.cos(direction-angle));if(n<d&&Math.abs(diff)<.26){nearest=e;d=n;}}
 player.aimAngle=angle;player.attack=1/w.rate;player.aimTime=player.attack+.16;hero.userData.shoot=w.id==='grimoire'?.32:w.id==='shade'?.20:.16;hero.userData.reloadPhase=0;hero.userData.reloadDuration=player.attack;
 if(w.id==='grimoire'){
  let distance=Math.min(w.range,8),nearestDistance=w.range;
  for(const e of targets){const len=Math.hypot(e.x-player.x,e.z-player.z),a=Math.atan2(e.x-player.x,e.z-player.z),offset=Math.abs(Math.atan2(Math.sin(a-angle),Math.cos(a-angle)));if(len<nearestDistance&&offset<.25){nearestDistance=len;distance=len;}}
  const x=T.MathUtils.clamp(player.x+Math.sin(angle)*distance,-61,61),z=T.MathUtils.clamp(player.z+Math.cos(angle)*distance,-61,61);
  riftStrikes.push({x,z,r:w.radius,damage:w.damage,echo:w.echo,delay:.28,angle});vfx.riftCast(x,z,w.radius,angle,false);sound.shot(w.id);return;
 }
 for(let i=0;i<w.count;i++){const a=angle+(i-(w.count-1)/2)*w.spread,m=vfx.projectile(w);m.position.set(player.x,1.15,player.z);m.rotation.y=a;scene.add(m);
 bullets.push({mesh:m,x:player.x,z:player.z,vx:Math.sin(a)*w.speed,vz:Math.cos(a)*w.speed,speed:w.speed,life:w.range/w.speed,damage:w.damage,kind:w.id,hits:new Set(),pierce:w.pierce,maxPierce:w.pierce,target:nearest,radius:w.radius,bounces:w.bounces,burn:w.burn,gravity:w.gravity,markDamage:w.markDamage,markRadius:w.markRadius,returnable:w.returning,returning:false,elapsed:0,turnAt:w.range/w.speed,trail:0});}
 impactChips(player.x+Math.sin(angle)*.65,player.z+Math.cos(angle)*.65,w.color,2);sound.shot(w.id);
}
function closestAutoTarget(range){let best=null,bestDistance=range*range;const consider=e=>{if(!e.alive)return;const distance=(e.x-player.x)**2+(e.z-player.z)**2;if(distance>=bestDistance||world.obstacles.some(o=>segmentDistance(o.x,o.z,player.x,player.z,e.x,e.z)<o.r+.12))return;best=e;bestDistance=distance;};for(const e of enemies)consider(e);if(boss)consider(boss);return best;}
function inflictStatus(e,b){if(!e.alive)return;if(b.burn){e.burnTime=3;e.burnDamage=Math.max(e.burnDamage||0,b.burn);} }
function updateStatus(e,dt){
 if(e.burnTime>0){const burnDt=Math.min(e.burnTime,dt);e.burnTime=Math.max(0,e.burnTime-dt);hurtEnemy(e,(e.burnDamage||0)*burnDt,false);}
 if(!e.alive)return;e.statusFX=(e.statusFX||0)-dt;if(e.statusFX<=0){e.statusFX=.2;if(e.burnTime>0)vfx.status('burn',e.x,e.z,e.size);if(e.slow>0)vfx.status('frost',e.x,e.z,e.size);}
}
function addGravity(x,z,rank){const old=fields.find(f=>Math.hypot(f.x-x,f.z-z)<1);if(old){old.life=Math.max(old.life,1.2+rank*.2);return;}if(fields.length>=3)fields.shift();fields.push({x,z,r:2.3+rank*.3,rank,life:1.2+rank*.2,pulse:.22});vfx.dark(x,z,2.3+rank*.3,true);}
function updateFields(dt){for(const f of fields){f.life-=dt;f.pulse-=dt;if(f.pulse<=0){f.pulse=.42;vfx.dark(f.x,f.z,f.r);}for(const e of [...enemies,...(boss?.alive?[boss]:[])]){if(!e.alive)continue;const d=Math.hypot(e.x-f.x,e.z-f.z);if(d<f.r&&d>.3){const amount=Math.min(d-.3,dt*(2+f.rank*.45)*(e===boss?.2:1));moveActor(world,e,(f.x-e.x)/d*amount,(f.z-e.z)/d*amount,e.size*.6);}}}fields=fields.filter(f=>f.life>0);}
function updateRiftStrikes(dt){for(const r of riftStrikes){r.delay-=dt;if(r.delay>0)continue;vfx.riftCast(r.x,r.z,r.r,r.angle,true);sound.impact('grimoire',true);for(const e of [...enemies,...(boss?.alive?[boss]:[])])if(e.alive&&Math.hypot(e.x-r.x,e.z-r.z)<r.r+e.size*.35){hurtEnemy(e,r.damage);if(state!=='playing')return;}if(r.echo){r.damage*=r.echo;r.echo=0;r.delay=.32;vfx.riftCast(r.x,r.z,r.r,r.angle,false);}else r.done=true;}riftStrikes=riftStrikes.filter(r=>!r.done);}
function updateShadowSpells(dt){if(heroId!=='wraith')return;const near=()=>[...enemies,...(boss?.alive?[boss]:[])].filter(e=>e.alive&&Math.hypot(e.x-player.x,e.z-player.z)<14).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z));
 for(const id of ['veil','chain','rift']){const rank=player.upgrades[id]||0;if(!rank)continue;player.spell[id]-=dt;if(player.spell[id]>0)continue;const foes=near();if(!foes.length)continue;player.spell[id]=id==='veil'?8:id==='chain'?7:9;const selected=id==='chain'?foes.slice(0,2+rank):foes.filter(e=>Math.hypot(e.x-player.x,e.z-player.z)<(id==='veil'?3.8:4.5));if(id==='rift'&&!selected.length){player.spell[id]=.5;continue;}
  if(id==='veil'){vfx.shadowSpell('veil',player.x,player.z);for(const e of selected){e.slow=Math.max(e.slow||0,2.5);hurtEnemy(e,10*rank);}}
  else if(id==='chain'){vfx.shadowSpell('chain',player.x,player.z,selected);for(const e of selected){e.slow=Math.max(e.slow||0,1.7);hurtEnemy(e,15*rank);}}
  else{const e=selected[0];vfx.shadowSpell('rift',e.x,e.z);for(const q of foes)if(Math.hypot(q.x-e.x,q.z-e.z)<2.8){hurtEnemy(q,30*rank);q.slow=Math.max(q.slow||0,1);}addGravity(e.x,e.z,Math.min(rank,2));}
  sound.spell(id);
 }
}
function updateVents(){if(mapId!=='ash')return;for(const vent of world.patches){if(vent.kind!=='vent')continue;const phase=(time+vent.phase)%4,warning=phase>=2.55&&phase<3.25,active=phase>=3.25&&phase<3.85;vent.marker.visible=warning||active;vent.marker.material.color.set(active?0xff603c:0xffc16d);vent.marker.material.opacity=active?.8:.58;if(active&&!vent.wasActive){vent.hitPlayer=false;vent.hitEnemies=new Set();vfx.fire(vent.x,vent.z,vent.r*.65);if(Math.hypot(player.x-vent.x,player.z-vent.z)<14)sound.tone(115,.25,.13,'sine',45);}if(active){if(!vent.hitPlayer&&Math.hypot(player.x-vent.x,player.z-vent.z)<vent.r){vent.hitPlayer=true;hitPlayer(12,vent.x,vent.z);if(state!=='playing')return;}for(const e of [...enemies,...(boss?.alive?[boss]:[])])if(e.alive&&!vent.hitEnemies.has(e)&&Math.hypot(e.x-vent.x,e.z-vent.z)<vent.r){vent.hitEnemies.add(e);hurtEnemy(e,18);if(state!=='playing')return;}}vent.wasActive=active;}}
function beginReturn(b){b.returning=true;b.hits.clear();b.pierce=b.maxPierce;b.life=3;}

function dash(){if(state!=='playing'||player.dash>0)return;renderer.shadowMap.needsUpdate=true;const input=movement(),angle=Math.hypot(input.x,input.z)>.1?Math.atan2((input.x+input.z)*.7071,(input.z-input.x)*.7071):hero.rotation.y;player.dash=2.3/(1+.12*(player.upgrades.stride||0));player.inv=.32;player.dashTime=heroId==='scout'?SCOUT_ROLL_DURATION:.24;player.dashAngle=angle;if(heroId==='silver'||heroId==='wraith'){const ox=player.x,oz=player.z;for(let d=heroId==='wraith'?4.7:5.5;d>0;d-=.2){const x=ox+Math.sin(angle)*d,z=oz+Math.cos(angle)*d;if(clearAt(world,x,z,.45)){player.x=x;player.z=z;break;}}if(heroId==='wraith'){vfx.shadowStep(ox,oz,player.x,player.z);sound.spell('dark');}else{burst('dark',ox,oz,1.3);burst('dark',player.x,player.z,1.5);}}else vfx.dust(player.x,player.z,1);sound.dodge(heroId!=='scout');}
function movement(){let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+stick.x,z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+stick.z;const d=Math.hypot(x,z);if(d>1){x/=d;z/=d;}return{x,z};}
function addZone(x,z,r,delay,damage,kind='poison'){const color=kind==='meteor'?0xfbd9a0:kind==='boss'?0xff876b:kind==='hex'?0x83dcb3:0xee9be4,ring=groundCue(color,r,kind==='meteor'?'glow':'danger',kind==='meteor'?.25:.58);ring.position.set(x,.09,z);scene.add(ring);zones.push({x,z,r,delay,life:delay+(kind==='boss'?.15:kind==='hex'?.25:2),damage,kind,mesh:ring,mist:0});if(kind==='poison')introduceCircle('poison','紫色毒雾','吐毒怪的毒雾会持续伤人，亮起后立刻离开。');else if(kind==='hex')introduceCircle('hex','青绿咒印','祭司的咒印会伤害并短暂减速，离开色块范围即可躲避。');else if(kind==='boss')introduceCircle('boss','红色裂地预警','首领即将攻击标记位置，先闪出范围。');else introduceCircle('meteor','金色陨火落点','这是你的升级法术，落下后伤害怪物。');}
function enemyWindup(e,a){
 e.tx=player.x;e.tz=player.z;e.attackAngle=a;e.attackMode=e.kind==='shaman'&&enemies.some(q=>q.alive&&q.hp<q.maxHp*.8&&Math.hypot(q.x-e.x,q.z-e.z)<6)?'heal':'hex';
 e.wind=({mushroom:.42,wolf:.48,golem:.95,spitter:.72,shaman:.85})[e.kind];
 const atSelf=e.kind==='golem'||e.kind==='shaman'&&e.attackMode==='heal',x=atSelf?e.x:e.tx,z=atSelf?e.z:e.tz,r=e.kind==='golem'?2.4:e.kind==='spitter'?2:e.kind==='shaman'?e.attackMode==='heal'?3:1.3:e.kind==='wolf'?1.05:.85;
 const color=e.kind==='spitter'?0xd7a3e6:e.kind==='shaman'?0x84dfb0:0xffad70;
 const healing=e.kind==='shaman'&&e.attackMode==='heal';if(healing)vfx.rise(x,z,0x89ddb3,1);const marker=healing?null:effect(e.kind==='mushroom'||e.kind==='wolf'?'target':'cue',x,z,color,r);if(marker?.userData.groundCue==='pounce')marker.rotation.z=a;if(marker){const entry=effects.at(-1);entry.life=entry.max=e.wind+.12;entry.telegraph=true;e.marker=entry;}
 if(e.kind==='mushroom'||e.kind==='wolf'||e.kind==='golem')introduceCircle('wind','橙色蓄力预警','橙色爪痕表示扑击落点，柔和色块表示震地范围；蓄力时侧移躲避。');
}
function finishEnemyWindup(e){if(e.marker){e.marker.life=0;e.marker=null;}
 if(e.kind==='mushroom'||e.kind==='wolf'){e.pounceDuration=e.kind==='wolf'?.24:.22;e.pounce=e.pounceDuration;e.landRecover=0;e.hit=false;e.cool=e.kind==='wolf'?1.7:1.35;return;}
 if(e.kind==='golem'){if(Math.hypot(player.x-e.x,player.z-e.z)<2.4)hitPlayer(e.damage,e.x,e.z);vfx.dust(e.x,e.z,2.4);impactChips(e.x,e.z,0xd2b692,7);sound.tone(83,.25,.11,'sine',38);e.cool=2.3;return;}
 if(e.kind==='spitter'){addZone(e.tx,e.tz,2,.75,e.damage,'poison');sound.tone(220,.15,.06,'sine',80);e.cool=3.1;return;}
 if(e.attackMode==='heal'){for(const ally of enemies)if(ally.alive&&Math.hypot(ally.x-e.x,ally.z-e.z)<6)ally.hp=Math.min(ally.maxHp,ally.hp+ally.maxHp*.16);burst('heal',e.x,e.z,3);}else addZone(e.tx,e.tz,1.3,.65,e.damage,'hex');
 e.cool=3.4;
}
// The ease offset returns to zero at landing, preserving total travel even when frame times vary.
function lungeEase(p){return .25*p+1.2/Math.PI*(1-Math.cos(Math.PI*p));}
function enemyPounce(e,dt){const ox=e.x,oz=e.z,base=e.kind==='wolf'?14:10,duration=e.pounceDuration,from=T.MathUtils.clamp(1-e.pounce/duration,0,1),to=Math.min(1,from+dt/duration);const step=base*(dt+duration*((lungeEase(to)-lungeEase(from))/lungeEase(1)-(to-from)));moveActor(world,e,Math.sin(e.attackAngle)*step,Math.cos(e.attackAngle)*step,e.size*.6);e.pounce=Math.max(0,e.pounce-dt);if(!e.hit&&segmentDistance(player.x,player.z,ox,oz,e.x,e.z)<e.size+.5){hitPlayer(e.damage,e.x,e.z);e.hit=true;}if(e.pounce<=0){e.landRecover=.14;impactChips(e.x,e.z,e.kind==='wolf'?0xb8c6d4:0xe0b38a,3);}return Math.hypot(e.x-ox,e.z-oz)/Math.max(dt,.001);}
function updateEnemies(dt){for(const e of enemies){if(!e.alive)continue;updateStatus(e,dt);if(!e.alive)continue;e.cool-=dt;e.hurt=Math.max(0,e.hurt-dt);e.slow=Math.max(0,e.slow-dt);e.stagger=Math.max(0,(e.stagger||0)-dt);const startX=e.x,startZ=e.z,dx=player.x-e.x,dz=player.z-e.z,d=Math.hypot(dx,dz),a=Math.atan2(dx,dz);let moving=0;
 if(e.stagger>0){e.wind=0;e.pounce=0;if(e.marker){e.marker.life=0;e.marker=null;}e.cool=Math.max(e.cool,.3);}
 else if(e.pounce>0)moving=enemyPounce(e,dt);
 else if(e.landRecover>0)e.landRecover=Math.max(0,e.landRecover-dt);
 else if(e.wind>0){e.wind-=dt;if(e.wind<=0)finishEnemyWindup(e);}
 else if(e.cool<=0&&d<(e.kind==='spitter'?15:e.kind==='shaman'?12:e.kind==='wolf'?3:1.4+e.size))enemyWindup(e,a);
 else{let tx=player.x,tz=player.z;if(['spitter','shaman'].includes(e.kind)){const tank=enemies.find(q=>q.alive&&q.kind==='golem'&&Math.hypot(q.x-e.x,q.z-e.z)<8);if(tank){const ta=Math.atan2(tank.x-player.x,tank.z-player.z);tx=tank.x+Math.sin(ta)*3;tz=tank.z+Math.cos(ta)*3;}else if(d<10){tx=e.x;tz=e.z;}}
 let ta=Math.atan2(tx-e.x,tz-e.z);if(e.kind==='wolf'&&d<8)ta+=Math.sin(time*2+e.id)*.2;if(e.kind==='mushroom')ta+=Math.sin(time*3+e.id)*.1;
 const speed=e.speed*(e.slow>0?.45:1)*(world.patches.some(p=>p.kind==='slow'&&Math.hypot(p.x-e.x,p.z-e.z)<p.r)?.75:1)*(e.kind==='mushroom'?.9+.18*Math.max(0,Math.sin(time*7+e.id)):1),step=speed*dt;if(Math.hypot(tx-e.x,tz-e.z)>.4){const ox=e.x,oz=e.z;moveActor(world,e,Math.sin(ta)*step,Math.cos(ta)*step,e.size*.6);if(Math.hypot(e.x-ox,e.z-oz)<step*.2)moveActor(world,e,Math.sin(ta+1.3)*step,Math.cos(ta+1.3)*step,e.size*.6);moving=Math.hypot(e.x-ox,e.z-oz)/Math.max(dt,.001);}}
 if(moving>.7&&d<13&&!['spitter','shaman'].includes(e.kind)){e.stepFX=(e.stepFX||0)-dt;if(e.stepFX<=0){e.stepFX=e.kind==='golem'?.34:.23;vfx.particle('smoke',mapId==='snow'?0xe0f4f8:mapId==='ash'?0xbb7963:0x95a77b,e.x,.13,e.z,{life:.3,size:[e.size*.28,.07,e.size*.28],velocity:[0,.15,0],opacity:.4,additive:false});}}
 const facing=e.wind>0||e.pounce>0?e.attackAngle:moving>.2?Math.atan2(e.x-startX,e.z-startZ):a,diff=Math.atan2(Math.sin(facing-e.mesh.rotation.y),Math.cos(facing-e.mesh.rotation.y));e.mesh.rotation.y+=T.MathUtils.clamp(diff*dt*8,-dt*6,dt*6);
 e.mesh.userData.pounce=e.pounce>0?e.pounce/e.pounceDuration:0;e.mesh.userData.attackMode=e.attackMode;e.mesh.position.set(e.x,0,e.z);animateActor(e.mesh,time+e.id,moving,e.wind,e.hurt);
 }enemies=enemies.filter(e=>e.alive);}
function spawnBoss(){const start=Math.random()*Math.PI*2;let spot=null;for(const radius of [14,17,11,20,8,23]){for(let i=0;i<24;i++){const a=start+i*Math.PI/12,x=T.MathUtils.clamp(player.x+Math.sin(a)*radius,-60,60),z=T.MathUtils.clamp(player.z+Math.cos(a)*radius,-60,60);if(clearAt(world,x,z,2)){spot={x,z};break;}}if(spot)break;}if(!spot)return;bossBorn=true;const m=actor('boss');boss={...spot,hp:1900,maxHp:1900,size:2,alive:true,mesh:m,cool:3,wind:0,recover:0,kind:'boss',phase:1,turn:0};m.position.set(boss.x,0,boss.z);scene.add(m);introduceEnemy('boss');toast('林心守卫苏醒 · 躲开蓄力，抓住破绽');burst('fire',boss.x,boss.z,4);sound.threat('boss');}
function updateBoss(dt){if(!boss?.alive)return;const b=boss;updateStatus(b,dt);if(!b.alive)return;const startX=b.x,startZ=b.z;b.slow=Math.max(0,(b.slow||0)-dt);b.hurt=Math.max(0,(b.hurt||0)-dt);b.cool-=dt;const a=Math.atan2(player.x-b.x,player.z-b.z),facing=(b.wind>0||b.charge>0)&&Number.isFinite(b.angle)?b.angle:a,diff=Math.atan2(Math.sin(facing-b.mesh.rotation.y),Math.cos(facing-b.mesh.rotation.y));b.mesh.rotation.y+=T.MathUtils.clamp(diff*dt*7,-dt*5,dt*5);if(b.hp<b.maxHp*.5&&b.phase===1){b.phase=2;toast('守卫狂暴 · 三重裂地！');}
 if(b.aoeWait>0){b.aoeWait-=dt;if(b.aoeWait<=0){b.recover=1.5;toast('裂地结束 · 趁破绽反击');}}
 else if(b.recover>0)b.recover-=dt;
 else if(b.charge>0){const ox=b.x,oz=b.z;b.x+=Math.sin(b.angle)*18*dt;b.z+=Math.cos(b.angle)*18*dt;b.x=Math.max(-60,Math.min(60,b.x));b.z=Math.max(-60,Math.min(60,b.z));if(segmentDistance(player.x,player.z,ox,oz,b.x,b.z)<2.2)hitPlayer(30,b.x,b.z);b.charge-=dt;if(b.charge<=0){b.recover=1.7;b.cool=3;toast('守卫露出破绽 · 伤害提高 25%');}}
 else if(b.wind>0){b.wind-=dt;if(b.wind<=0){b.charge=.7;}}
 else if(b.cool<=0){b.turn++;if(b.turn%2){b.wind=1.2;b.angle=a;introduceCircle('charge','橙色冲撞轨迹','首领沿地面的箭头方向冲锋；横向闪避。');const lane=groundCue(0xffc18c,1,'lane',.65);lane.position.set(b.x+Math.sin(a)*6.3,.09,b.z+Math.cos(a)*6.3);lane.rotation.z=a+Math.PI;lane.scale.set(2.2,6.3,1);scene.add(lane);effects.push({mesh:lane,kind:'lane',life:1.2,max:1.2});toast('守卫冲撞 · 向侧面闪避');}else{for(const offset of b.phase===2?[-4,0,4]:[0])addZone(player.x+Math.cos(a)*offset,player.z-Math.sin(a)*offset,b.phase===2?2.3:3,1.5,27,'boss');b.aoeWait=1.5;b.cool=5;}}
 else{moveActor(world,b,Math.sin(a)*1.8*dt,Math.cos(a)*1.8*dt,1.5);}
 b.mesh.position.set(b.x,0,b.z);animateActor(b.mesh,time,Math.hypot(b.x-startX,b.z-startZ)/Math.max(dt,.001),b.wind,b.hurt);}
function updateSites(dt){for(const s of world.sites){if(s.crystal){s.crystal.rotation.y+=dt;s.crystal.position.y=1.1+Math.sin(time*2)*.12;}const d=Math.hypot(player.x-s.x,player.z-s.z);s.ring.visible=!s.claimed&&(d<11||s.state==='ready');s.ring.material.opacity=s.state==='ready'?.48:.20;if(s.claimed)continue;if(!s.state&&d<6){s.state='warning';s.timer=2;introduceCircle('site','探索目标微光','石门祭坛和补给箱是探索目标。清理周围守卫，再靠近领取奖励。');toast(s.type==='altar'?'远古祭坛 · 精锐守卫即将苏醒':'猎人补给 · 清理守卫领取治疗');}if(s.state==='warning'){s.timer-=dt;if(s.timer<=0){s.state='guarded';s.guards=[];for(let i=0;i<4;i++){const a=i*Math.PI/2,e=spawn(i===0?'golem':i===1?'spitter':'wolf',s.x+Math.sin(a)*4,s.z+Math.cos(a)*4,s);if(e)s.guards.push(e);}}}if(s.state==='guarded'&&s.guards.every(e=>!e.alive)){s.state='ready';toast('守卫已清除 · 靠近领取奖励');}if(s.state==='ready'&&d<2.5){s.claimed=true;s.ring.visible=false;burst('heal',s.x,s.z,3);if(s.type==='altar'){player.pending++;toast('祭坛祝福 · 获得一项技能');}else{player.hp=Math.min(player.maxHp,player.hp+player.maxHp*.4);for(const o of orbs)o.attract=true;toast('补给已领取 · 治疗 40%，吸引所有灵光');}}}}
function update(dt){const rollStart=heroId==='scout'?player.dashTime:0;time+=dt;simTimer+=dt;player.xpFlash=Math.max(0,(player.xpFlash||0)-dt);player.attack=Math.max(0,player.attack-dt);player.dash=Math.max(0,player.dash-dt);player.inv=Math.max(0,player.inv-dt);player.hurt=Math.max(0,player.hurt-dt);player.hexSlow=Math.max(0,player.hexSlow-dt);player.dashTime=Math.max(0,player.dashTime-dt);player.aimTime=Math.max(0,(player.aimTime||0)-dt);if(attackMode==='manual'&&!touch&&mouseAim.valid)refreshMouseAim();const input=movement(),moving=Math.hypot(input.x,input.z),slow=world.patches.some(p=>p.kind==='slow'&&Math.hypot(p.x-player.x,p.z-player.z)<p.r)?.72:1,speed=6.5*(1+.08*(player.upgrades.stride||0))*slow*(player.hexSlow>0?.78:1);
 // Camera-oriented input keeps up/down aligned with the screen.
 const dx=(input.x+input.z)*.7071,dz=(input.z-input.x)*.7071,oldX=player.x,oldZ=player.z;
 if(rollStart>0){const distance=rollTravel(player.dashTime)-rollTravel(rollStart);moveActor(world,player,Math.sin(player.dashAngle)*distance,Math.cos(player.dashAngle)*distance);}else moveActor(world,player,dx*speed*dt,dz*speed*dt);
 const movedX=player.x-oldX,movedZ=player.z-oldZ,actualSpeed=rollStart>0?moving*speed:Math.hypot(movedX,movedZ)/Math.max(dt,.001),travelAngle=actualSpeed>.05?Math.atan2(movedX,movedZ):null;
 if(moving>.1)player.angle=Math.atan2(dx,dz);
 const rolling=heroId==='scout'&&player.dashTime>0;
 const autoTarget=attackMode==='auto'?closestAutoTarget(weaponStats(player).range):null;if(attackMode==='auto'){aimInput.hasAim=!!autoTarget;if(autoTarget)aimInput.angle=Math.atan2(autoTarget.x-player.x,autoTarget.z-player.z);}
 const desired=rolling?player.dashAngle:aimInput.hasAim?aimInput.angle:player.aimTime>0?player.aimAngle:player.angle;
 const difference=Math.atan2(Math.sin(desired-hero.rotation.y),Math.cos(desired-hero.rotation.y)),turn=T.MathUtils.clamp(difference*(1-Math.exp(-dt*14)),-12*dt,12*dt);
 hero.rotation.y+=turn;hero.position.set(player.x,0,player.z);
 Object.assign(hero.userData,{dashTime:player.dashTime,travelAngle,aimActive:aimInput.held||!!autoTarget||player.aimTime>0,aimAngle:aimInput.hasAim?aimInput.angle:player.aimTime>0?player.aimAngle:undefined,turnRate:turn/Math.max(dt,.001),reloadPhase:hero.userData.reloadDuration?1-player.attack/hero.userData.reloadDuration:1});
 hero.userData.shoot=Math.max(0,(hero.userData.shoot||0)-dt);animateActor(hero,time,actualSpeed,hero.userData.shoot,player.hurt);
 if(heroId==='silver'&&player.dashTime>0)hero.scale.setScalar(.65+.35*(1-player.dashTime/.24));else hero.scale.setScalar(1);
 const aimOffset=Math.abs(Math.atan2(Math.sin(aimInput.angle-hero.rotation.y),Math.cos(aimInput.angle-hero.rotation.y))),aligned=aimOffset<.26;
 if((attackMode==='auto'?!!autoTarget&&aligned:aimInput.held&&(player.weaponId!=='crossbow'||aligned))&&player.attack<=0&&player.dashTime===0)shoot();spawnTimer-=dt;if(spawnTimer<=0){spawnTimer=Math.max(.65,2-time*.007);const kinds=time<25?['mushroom']:time<55?['mushroom','wolf']:['mushroom','wolf','golem','spitter','shaman'];spawn(kinds[Math.floor(Math.random()*kinds.length)]);}if(time>=waveTimer){waveTimer=time+30;toast('兽群从四周接近 · 留意突围路线');sound.threat('wave');for(let i=0;i<6;i++){const a=i/6*Math.PI*1.7,r=17;spawn(i%3===0?'golem':'wolf',player.x+Math.sin(a)*r,player.z+Math.cos(a)*r);}}
 updateRiftStrikes(dt);if(state!=='playing')return;updateFields(dt);updateVents();if(state!=='playing')return;updateEnemies(dt);if(state!=='playing')return;updateBoss(dt);if(state!=='playing')return;
 const targets=()=>[...enemies,...(boss?.alive?[boss]:[])];
 for(const b of bullets){b.elapsed+=dt;if(b.returnable&&!b.returning&&b.elapsed>=b.turnAt)beginReturn(b);const ox=b.x,oz=b.z;
 if(b.returning){const d=Math.hypot(player.x-b.x,player.z-b.z);if(d<.65){b.life=0;continue;}const a=Math.atan2(player.x-b.x,player.z-b.z);b.vx=Math.sin(a)*b.speed;b.vz=Math.cos(a)*b.speed;}
 else if(b.kind==='dark'&&b.target?.alive){const a=Math.atan2(b.target.x-b.x,b.target.z-b.z),blend=1-Math.exp(-dt*6);b.vx=T.MathUtils.lerp(b.vx,Math.sin(a)*b.speed,blend);b.vz=T.MathUtils.lerp(b.vz,Math.cos(a)*b.speed,blend);}
 b.x+=b.vx*dt;b.z+=b.vz*dt;b.life-=dt;b.mesh.position.set(b.x,1.15,b.z);if(['shuriken','shadowblade'].includes(b.kind))b.mesh.rotation.y+=dt*24;else b.mesh.rotation.y=Math.atan2(b.vx,b.vz);if(!b.returning&&!clearAt(world,b.x,b.z,.1))b.life=0;
 b.trail-=dt;if(b.trail<=0&&['fire','dark','crossbow','shade','shadowblade'].includes(b.kind)){b.trail=b.kind==='crossbow'?.048:.075;vfx.particle('ember',b.kind==='fire'?0xffa449:b.kind==='crossbow'?0xc5eaff:0xa778f1,b.x,1.15,b.z,{life:.18,size:b.kind==='crossbow'?[.035,.035,.09]:[.065,.065,.12],opacity:.6});}
 for(const e of targets()){if(!e.alive||b.hits.has(e.id??'boss')||b.life<=0||b.pierce<=0)continue;if(segmentDistance(e.x,e.z,ox,oz,b.x,b.z)<e.size+.2){b.hits.add(e.id??'boss');const strong=b.kind==='crossbow'&&registerCrossbowHit(player,e.id??'boss',time);hurtEnemy(e,b.damage*(strong?1.35:1));inflictStatus(e,b);sound.impact(b.kind,strong);if(b.kind==='shuriken'||b.kind==='shadowblade')vfx.bladeImpact(e.x,e.z,Math.atan2(b.vx,b.vz),b.kind==='shadowblade');else if(b.kind==='rifle'||b.kind==='shotgun')impactChips(e.x,e.z,0xffdf97,2);if(b.kind==='crossbow'){vfx.boltImpact(e.x,e.z,strong);if(strong&&e.alive&&e!==boss){const d=Math.hypot(e.x-player.x,e.z-player.z)||1;moveActor(world,e,(e.x-player.x)/d*1.8,(e.z-player.z)/d*1.8,e.size*.6);e.mesh.position.set(e.x,0,e.z);e.stagger=.3;e.hurt=.3;}}
 if(b.kind==='shade'){const marked=registerShadowHit(e,time);vfx.shadowMark(e.x,e.z,marked);if(marked){sound.spell('rift');hurtEnemy(e,b.markDamage);for(const other of targets())if(other!==e&&other.alive&&Math.hypot(other.x-e.x,other.z-e.z)<b.markRadius)hurtEnemy(other,b.markDamage*.5);}}
 if(['fire','dark'].includes(b.kind)){if(b.kind==='fire')vfx.fire(e.x,e.z,b.radius);else vfx.dark(e.x,e.z,b.radius);sound.spell(b.kind);if(b.gravity)addGravity(e.x,e.z,b.gravity);for(const other of targets())if(other!==e&&other.alive&&Math.hypot(other.x-e.x,other.z-e.z)<b.radius){hurtEnemy(other,b.damage*.65);inflictStatus(other,b);}}
 if(b.bounces>0){const next=targets().filter(q=>q.alive&&!b.hits.has(q.id??'boss')&&Math.hypot(q.x-e.x,q.z-e.z)<7).sort((a,c)=>Math.hypot(a.x-e.x,a.z-e.z)-Math.hypot(c.x-e.x,c.z-e.z))[0];if(next){const a=Math.atan2(next.x-e.x,next.z-e.z);b.x=e.x;b.z=e.z;b.vx=Math.sin(a)*b.speed;b.vz=Math.cos(a)*b.speed;b.damage*=.75;b.bounces--;b.life=7/b.speed;b.mesh.position.set(b.x,1.15,b.z);break;}}
 b.pierce--;if(b.pierce<=0){if(b.returnable&&!b.returning)b.turnAt=0;else b.life=0;}
 }}
 }bullets=bullets.filter(b=>{if(b.life>0)return true;scene.remove(b.mesh);return false;});if(state!=='playing')return;
 for(const z of zones){z.delay-=dt;z.life-=dt;z.mesh.material.opacity=z.kind==='meteor'?.25:z.delay>0?.58:.75;if(z.delay<=0){z.mesh.material.color.set(z.kind==='meteor'?0xffbc63:z.kind==='boss'?0xff6b48:z.kind==='hex'?0x57bc91:0xaa60cc);z.mist-=dt;if(z.kind==='poison'&&z.mist<=0){z.mist=.3;vfx.mist(z.x,z.z,z.r);}if(!z.burst){z.burst=true;if(z.kind==='meteor'){vfx.fire(z.x,z.z,z.r,true);sound.spell('fire');z.mesh.visible=false;}else burst(z.kind==='boss'?'fire':z.kind==='hex'?'hex':'dark',z.x,z.z,z.r);if(z.kind==='meteor')for(const e of targets())if(Math.hypot(e.x-z.x,e.z-z.z)<z.r)hurtEnemy(e,z.damage);}if(z.kind!=='meteor'&&Math.hypot(player.x-z.x,player.z-z.z)<z.r+.4){hitPlayer(z.damage,z.x,z.z);if(z.kind==='hex')player.hexSlow=1.2;}}}
 zones=zones.filter(z=>{if(z.life>0)return true;scene.remove(z.mesh);disposeCue(z.mesh);return false;});if(state!=='playing')return;
 for(const id of ['fire','ice','storm']){const rank=player.upgrades[id]||0;if(!rank)continue;player.spell[id]-=dt;if(player.spell[id]>0)continue;const near=targets().filter(e=>e.alive&&Math.hypot(e.x-player.x,e.z-player.z)<17).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z));if(!near.length)continue;player.spell[id]=id==='ice'?7:5.5;if(id==='fire'){const e=near[0];addZone(e.x,e.z,3.5,.5,35*rank,'meteor');zones[zones.length-1].life=.65;vfx.meteor(e.x,e.z);}else if(id==='ice'){vfx.ice(player.x,player.z,5);sound.spell('ice');for(const e of near)if(Math.hypot(e.x-player.x,e.z-player.z)<5){hurtEnemy(e,20*rank);e.slow=2+rank*.35;}}else{let x=near[0].x,z=near[0].z,first=true;for(const e of near.slice(0,2+rank)){lightning(x,z,e.x,e.z,first);hurtEnemy(e,27*rank);first=false;x=e.x;z=e.z;}}}
 updateShadowSpells(dt);if(state!=='playing')return;
 for(const o of orbs){const d=Math.hypot(o.x-player.x,o.z-player.z);if(d<3+(player.upgrades.magnet||0)*2||o.attract){o.attract=true;const a=Math.atan2(player.x-o.x,player.z-o.z),s=Math.min(d,dt*15);o.x+=Math.sin(a)*s;o.z+=Math.cos(a)*s;}o.mesh.position.set(o.x,.45+Math.sin(time*3)*.08,o.z);o.mesh.rotation.y+=dt*2;if(d<.6){collectExperience(o.xp);o.dead=true;scene.remove(o.mesh);}}
 orbs=orbs.filter(o=>!o.dead);if(orbs.length>350){const dropped=orbs.splice(0,orbs.length-350);for(const o of dropped)scene.remove(o.mesh);}updateSites(dt);if(time>=180&&!bossBorn)spawnBoss();if(player.pending)upgrade();}
function collectExperience(n){const previous=player.level;player.xpGain=(player.xpFlash>0?player.xpGain:0)+n;player.xpFlash=.9;grantExperience(player,n);if(player.level>previous){sound.level();vfx.rise(player.x,player.z,0x8ef9ff,2.2);toast('升级至 Lv.'+player.level+' · 选择新的力量');}else sound.pickup();}
function updateEffects(dt){vfx.update(dt);for(const e of effects){e.life-=dt;const p=1-e.life/e.max;if(e.kind==='line')continue;if(e.kind==='lane'){e.mesh.material.opacity=.5+.15*p;continue;}if(e.kind==='cue'||e.kind==='target')e.mesh.material.opacity=.48+.2*p;const scale=e.telegraph?e.r:e.kind==='spike'?e.r*Math.sin(Math.PI*Math.min(.99,p)):e.r*(1-p*.7);e.mesh.scale.setScalar(Math.max(.001,scale));if(e.vy)e.mesh.position.y+=dt*e.vy;if(e.vx)e.mesh.position.x+=dt*e.vx;if(e.vz)e.mesh.position.z+=dt*e.vz;}effects=effects.filter(e=>{if(e.life>0)return true;scene.remove(e.mesh);disposeCue(e.mesh);if(e.kind==='line'){e.mesh.geometry.dispose();e.mesh.material.dispose();}return false;});}
function updateCamera(dt){const menuMode=state==='menu',target=new T.Vector3(player.x+(menuMode?-2:0),menuMode?1.1:.5,player.z+(menuMode?2:0));camTarget.lerp(target,1-Math.exp(-dt*8));const distance=menuMode?8.5:touch&&innerHeight>innerWidth?27:touch?20:24;camera.position.set(camTarget.x+distance*.7,camTarget.y+distance*(menuMode?.48:1),camTarget.z+distance*.7);if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;}camera.lookAt(camTarget);sun.position.set(player.x+15,30,player.z+12);sun.target.position.set(player.x,0,player.z);}
function updateHUD(){const ratio=player.hp/player.maxHp;$('#level').textContent='Lv.'+player.level;$('.hp i').style.width=ratio*100+'%';$('.hp i').style.background=ratio<.3?'#e56b65':'';$('.hp b').textContent=Math.ceil(player.hp)+' / '+player.maxHp;const needed=experienceNeeded(player.level);$('.xp i').style.width=player.xp/needed*100+'%';$('.xp').setAttribute('aria-valuenow',player.xp);$('.xp').setAttribute('aria-valuemax',needed);$('#xp-value').textContent=player.xp+' / '+needed;$('#xp-next').textContent='→ Lv.'+(player.level+1);$('.status').classList.toggle('gaining',player.xpFlash>0);$('#xp-gain').textContent=player.xpFlash>0?'+'+player.xpGain+' 经验':'';$('#timer').textContent=String(Math.floor(time/60)).padStart(2,'0')+':'+String(Math.floor(time%60)).padStart(2,'0');$('#kills').textContent='击败 '+kills;$('#boss-hud').hidden=!boss?.alive;if(boss?.alive){$('#boss-hud i').style.width=Math.max(0,boss.hp/boss.maxHp)*100+'%';$('#boss-hud span').textContent=boss.recover>0?'破绽 · 伤害 +25%':'林心守卫 · '+(boss.phase===2?'狂暴':'觉醒');}$('#objective').textContent=boss?.alive?'击败林心守卫，完成远征':time<20?'探索地图上的补给与祭坛':'守卫苏醒倒计时 '+Math.max(0,Math.ceil(180-time))+' 秒 · 探索 '+world.sites.filter(s=>s.claimed).length+'/2';$('#hint').textContent=ratio<.3?'生命危险 · 闪避并寻找补给':weaponFor(heroId,weaponIndex).name+' · '+(world.patches.some(p=>p.kind==='slow'&&Math.hypot(p.x-player.x,p.z-player.z)<p.r)?MAPS[mapId].slow+'减速':'移动迎战');$('#dash').textContent=player.dash>0?player.dash.toFixed(1)+'s':heroId==='silver'?'瞬移':heroId==='wraith'?'影步':'翻滚';const nextSkills=(player.weaponPath?'<span class=weapon-path>'+WEAPON_PATHS[player.weaponPath.id].name+' '+player.weaponPath.rank+'阶</span>':'')+Object.entries(player.upgrades).map(([id,n])=>'<span>'+({power:'锋芒',haste:'疾风',fire:'陨火',ice:'冰环',storm:'落雷',veil:'暗幕',chain:'缚影',rift:'裂隙',vitality:'坚韧',stride:'步伐',magnet:'牵引'}[id])+' '+n+'</span>').join('');if(nextSkills!==skillsHTML){$('#skills').innerHTML=nextSkills;skillsHTML=nextSkills;}$('#damage-edge').style.opacity=player.hurt>0?.6:ratio<.3?.16+Math.sin(time*4)*.05:0;
 const c=$('#map canvas').getContext('2d');c.fillStyle='#193d36';c.fillRect(0,0,144,144);c.strokeStyle='#43664e';c.strokeRect(6,6,132,132);c.fillStyle='#72947a';for(const o of world.obstacles)c.fillRect(72+o.x,72+o.z,1.5,1.5);for(const s of world.sites){c.fillStyle=s.claimed?'#608371':s.type==='altar'?'#ceb3ff':'#f0d694';c.beginPath();c.arc(72+s.x,72+s.z,4,0,Math.PI*2);c.fill();c.font='10px sans-serif';c.textAlign='center';c.fillText(s.type==='altar'?'技能':'治疗',72+s.x,64+s.z);}c.fillStyle='#e78275';for(const e of enemies)if(e.alive)c.fillRect(72+e.x,72+e.z,2,2);if(boss?.alive){c.fillStyle='#ffb070';c.fillRect(69+boss.x,69+boss.z,6,6);}c.fillStyle='#fff9d6';c.beginPath();c.arc(72+player.x,72+player.z,3,0,Math.PI*2);c.fill();}
function clearAttack(){aimInput.held=false;aimInput.hasAim=false;mouseAim.valid=false;aimStick.id=null;const knob=$('#aim-stick i');if(knob)knob.style.transform='';}
function refreshMouseAim(){const r=canvas.getBoundingClientRect(),x=(mouseAim.x-r.left)/r.width*2-1,y=1-(mouseAim.y-r.top)/r.height*2;aimRay.setFromCamera({x,y},camera);if(aimRay.ray.intersectPlane(groundPlane,temp)){const dx=temp.x-player.x,dz=temp.z-player.z;if(Math.hypot(dx,dz)>.35){aimInput.angle=Math.atan2(dx,dz);aimInput.hasAim=true;}}}
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLElement&&e.target.closest('input,select,textarea,[contenteditable="true"]'))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','escape'].includes(k))e.preventDefault();if(k==='escape'){pause();return;}if(k==='shift'||k===' '){dash();return;}if(state==='playing')keys.add(k);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('pointermove',e=>{if(touch||state!=='playing'||attackMode!=='manual'||e.pointerType!=='mouse')return;mouseAim.x=e.clientX;mouseAim.y=e.clientY;mouseAim.valid=true;});
canvas.addEventListener('pointerdown',e=>{if(touch||state!=='playing'||attackMode!=='manual'||e.button!==0)return;e.preventDefault();mouseAim.x=e.clientX;mouseAim.y=e.clientY;mouseAim.valid=true;refreshMouseAim();aimInput.held=true;});
window.addEventListener('pointerup',e=>{if(e.pointerType==='mouse'&&e.button===0)aimInput.held=false;});
window.addEventListener('pointercancel',()=>{aimInput.held=false;});
function releaseStick(){stick.x=stick.z=0;stick.id=null;$('#joystick i').style.transform='';}
function moveStick(e){if(state!=='playing')return;const r=$('#joystick').getBoundingClientRect(),x=e.clientX-r.x-r.width/2,z=e.clientY-r.y-r.height/2,d=Math.hypot(x,z),f=Math.min(1,34/(d||1));stick.x=x*f/34;stick.z=z*f/34;$('#joystick i').style.transform=`translate(${x*f}px,${z*f}px)`;}
$('#joystick').addEventListener('pointerdown',e=>{if(state!=='playing')return;e.preventDefault();stick.id=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);moveStick(e);});$('#joystick').addEventListener('pointermove',e=>{if(stick.id===e.pointerId)moveStick(e);});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#joystick').addEventListener(name,releaseStick);$('#dash').addEventListener('pointerdown',e=>{e.preventDefault();dash();});
function moveAimStick(e){if(state!=='playing'||attackMode!=='manual')return;const r=$('#aim-stick').getBoundingClientRect(),x=e.clientX-r.x-r.width/2,z=e.clientY-r.y-r.height/2,d=Math.hypot(x,z),f=Math.min(1,34/(d||1));$('#aim-stick i').style.transform=`translate(${x*f}px,${z*f}px)`;if(d>12){aimInput.angle=Math.atan2((x+z)*.7071,(z-x)*.7071);aimInput.hasAim=true;aimInput.held=true;}}
function releaseAimStick(e){if(aimStick.id===null||(e&&e.pointerId!==aimStick.id))return;aimStick.id=null;aimInput.held=false;$('#aim-stick i').style.transform='';}
$('#aim-stick').addEventListener('pointerdown',e=>{if(state!=='playing'||attackMode!=='manual'||aimStick.id!==null)return;e.preventDefault();aimStick.id=e.pointerId;aimInput.angle=hero.rotation.y;aimInput.hasAim=true;aimInput.held=true;e.currentTarget.setPointerCapture(e.pointerId);moveAimStick(e);});
$('#aim-stick').addEventListener('pointermove',e=>{if(aimStick.id===e.pointerId)moveAimStick(e);});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#aim-stick').addEventListener(name,releaseAimStick);
window.addEventListener('blur',()=>{keys.clear();releaseStick();clearAttack();if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});function resizeRendering(){renderWidth=innerWidth;renderHeight=innerHeight;renderDpr=devicePixelRatio;renderer.setPixelRatio(renderPixelRatio(renderWidth,renderHeight,renderDpr,touch,renderBudget.quality));renderer.setSize(renderWidth,renderHeight,false);camera.aspect=renderWidth/Math.max(1,renderHeight);camera.updateProjectionMatrix();renderer.shadowMap.needsUpdate=true;}
window.addEventListener('resize',()=>{resizeRendering();renderBudget.reset();releaseStick();releaseAimStick();});resizeRendering();
renderChoices();setAttackMode(attackMode);
for(const b of document.querySelectorAll('#menu button'))b.disabled=true;
try{await loadHeroAssets((n,total)=>{$('#asset-loading span').textContent=(n===total?'正在布置场景…':'正在载入人物 · '+Math.round(n/total*100)+'%');});$('#asset-loading').hidden=true;for(const b of document.querySelectorAll('#menu button'))b.disabled=false;build();}
catch(e){$('#asset-loading span').textContent='角色资源加载失败，请检查网络后重试。';$('#asset-retry').hidden=false;$('#asset-retry').onclick=()=>location.reload();throw e;}
let sceneryTime=0;
function frame(now){const frameSeconds=(now-last)/1000,dt=Math.min(.04,frameSeconds);last=now;const active=state==='playing'||state==='menu';if(renderWidth!==innerWidth||renderHeight!==innerHeight||renderDpr!==devicePixelRatio){resizeRendering();renderBudget.reset();}else if(active&&renderBudget.sample(frameSeconds))resizeRendering();if(active){shadowClock+=dt;const shadowInterval=state==='menu'||touch||renderBudget.quality<.8?1/20:1/30;if(shadowClock>=shadowInterval){renderer.shadowMap.needsUpdate=true;shadowClock%=shadowInterval;}}if(state==='playing'||state==='menu'){sceneryTime+=dt;animateWorld(world,sceneryTime,player.x,player.z);}sound.update(dt,{map:mapId,mode:state,boss:!!boss?.alive,pressure:Math.min(1,enemies.filter(e=>e.alive&&Math.hypot(e.x-player.x,e.z-player.z)<12).length/10)});if(state==='playing'){update(dt);updateEffects(dt);}else if(state==='menu'){animateActor(hero,now/1000,.3);hero.rotation.y=.65+Math.sin(now/3000)*.2;world.light.intensity=9+Math.sin(now/100)*1.5;}for(let i=0;i<world.motes.length;i++){const m=world.motes[i];m.position.y+=Math.sin(now/1200+i)*dt*.15;m.scale.setScalar(.5+Math.sin(now/550+i)*.3);}world.fire.scale.y=1+Math.sin(now/90)*.3;
 if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('#toast').style.opacity=0;}if(state==='playing'&&encounterTime>0){encounterTime-=dt;if(encounterTime<=0)showNextIntroduction();}shake=Math.max(0,shake-dt);updateCamera(dt);uiTime+=dt;if(uiTime>.1&&state!=='menu'){uiTime=0;updateHUD();}renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.game3d={get renderQuality(){return renderBudget.quality;},get audio(){return sound;},get hero(){return hero;},get state(){return state;},get player(){return player;},get enemies(){return enemies;},get boss(){return boss;},get world(){return world;},get time(){return time;},get renderer(){return renderer;},get camera(){return camera;},get controls(){return aimInput;},get vfx(){return vfx;},get bullets(){return bullets;},get fields(){return fields;},get riftStrikes(){return riftStrikes;},get zones(){return zones;},start,pause,resume,menu,dash,spawn,spawnBoss,step(dt){if(state==='playing')update(dt);},grant(n){collectExperience(n);upgrade();},damage:hitPlayer,hurtEnemy,select(hero,map,index){heroId=hero;mapId=map;weaponIndex=index;renderChoices();build();}};
