import{loadHeroAssets,disposeHero}from'./skinned-hero.js?v=2';
import{GameAudio}from'./audio.js?v=2';
import * as T from './vendor/three.module.js';
import{MAPS,WEAPONS,ENEMIES,weaponFor,experienceNeeded,grantExperience,chooseUpgrades,segmentDistance}from'./rules.js';
import{actor,animateActor,buildWorld,clearAt,moveActor,mesh,mat}from'./world.js?v=2';
const $=s=>document.querySelector(s),touch=matchMedia('(pointer:coarse)').matches;
document.body.classList.toggle('touch',touch);
const canvas=$('#world');let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});}catch(e){$('#error').hidden=false;$('#error').textContent='无法启动 3D 画面。请使用支持 WebGL 的较新浏览器，并开启硬件加速。';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,touch?1.35:1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,180);scene.add(new T.HemisphereLight(0xc8f5ed,0x273c39,2.8));
const sun=new T.DirectionalLight(0xffe3b3,3.2);sun.position.set(15,30,12);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-28,right:28,top:28,bottom:-28,near:.5,far:80});sun.shadow.bias=-.001;sun.shadow.normalBias=.012;scene.add(sun,sun.target);
const glowCanvas=document.createElement('canvas');glowCanvas.width=glowCanvas.height=64;const glowCtx=glowCanvas.getContext('2d'),gradient=glowCtx.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'rgba(255,255,255,.8)');gradient.addColorStop(.3,'rgba(255,255,255,.35)');gradient.addColorStop(1,'rgba(255,255,255,0)');glowCtx.fillStyle=gradient;glowCtx.fillRect(0,0,64,64);const glowTexture=new T.CanvasTexture(glowCanvas),glowMaterials=new Map();
function glow(color,size){if(!glowMaterials.has(color))glowMaterials.set(color,new T.SpriteMaterial({map:glowTexture,color,transparent:true,opacity:.6,depthWrite:false,blending:T.AdditiveBlending}));const s=new T.Sprite(glowMaterials.get(color));s.scale.set(size,size,1);return s;}
const rim=new T.DirectionalLight(0x93cfd9,1.3);rim.position.set(-10,10,-15);scene.add(rim);
let world,hero,heroId='silver',mapId='forest',weaponIndex=0,state='menu',time=0,kills=0,player,enemyId=0,enemies=[],bullets=[],orbs=[],effects=[],zones=[],spawnTimer=2,waveTimer=32,boss=null,bossBorn=false,toastTimer=0,shake=0,simTimer=0;
const keys=new Set(),stick={x:0,z:0,id:null},camTarget=new T.Vector3(),temp=new T.Vector3();let last=performance.now(),uiTime=0;
const sound=new GameAudio();
function syncAudioUI(){const active=sound.ctx?.state==='running';$('#sound').textContent=sound.muted?'声音：关':active?'声音：开':'开启声音';$('#sound').setAttribute('aria-pressed',String(!sound.muted));$('#music-volume').value=Math.round(sound.musicVolume*100);$('#sfx-volume').value=Math.round(sound.sfxVolume*100);$('#music-value').textContent=Math.round(sound.musicVolume*100)+'%';$('#sfx-value').textContent=Math.round(sound.sfxVolume*100)+'%';}
async function unlockAudio(){const ok=await sound.init();syncAudioUI();if(!ok)toast('声音尚未开启，请点右上角“开启声音”重试');}
for(const bus of ['music','sfx'])$('#'+bus+'-volume').addEventListener('input',e=>{sound.setVolume(bus,Number(e.target.value)/100);unlockAudio();syncAudioUI();});
syncAudioUI();
function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;toastTimer=3;}
function effect(kind,x,z,color,r=1,y=.15){if(effects.length>170)return;let m;if(kind==='ring'){m=mesh('TorusGeometry',[1,.045,4,40],color,x,y,z,null,true);m.rotation.x=Math.PI/2;}else if(kind==='spike')m=mesh('ConeGeometry',[.2,1.5,5],color,x,y,z,null,true);else m=mesh('SphereGeometry',[1,7,5],color,x,y,z,null,true);if(['spark','meteor'].includes(kind))m.add(glow(color,5));scene.add(m);effects.push({mesh:m,kind,life:kind==='ring'?.6:.55,max:kind==='ring'?.6:.55,r,vy:kind==='spark'?2.5:kind==='meteor'?-10:0,x,z});return m;}
function burst(kind,x,z,r=2){const color=kind==='ice'?0x9beeff:kind==='dark'?0xc19aff:kind==='heal'?0xbdf1a4:0xffad55;effect('ring',x,z,color,r);for(let i=0;i<10;i++){const a=i*Math.PI/5,d=r*(.3+Math.random()*.5);effect(kind==='ice'?'spike':'spark',x+Math.cos(a)*d,z+Math.sin(a)*d,color,kind==='ice'?.65:.1+Math.random()*.15,kind==='ice'?.4:.5);}sound.spell(kind);}
function lightning(ax,az,bx,bz){const points=[];for(let i=0;i<=7;i++){const f=i/7;points.push(new T.Vector3(ax+(bx-ax)*f+(i&&i<7?(Math.random()-.5)*.4:0),1+Math.sin(f*Math.PI)*.8,az+(bz-az)*f));}const line=new T.Line(new T.BufferGeometry().setFromPoints(points),new T.LineBasicMaterial({color:0xfff6b7}));scene.add(line);effects.push({mesh:line,kind:'line',life:.2,max:.2,r:1});sound.spell('storm');}
function clearObjects(){for(const list of [enemies,bullets,orbs,effects,zones])for(const o of list){scene.remove(o.mesh);if(o.kind==='line'){o.mesh.geometry.dispose();o.mesh.material.dispose();}}if(boss)scene.remove(boss.mesh);enemies=[];bullets=[];orbs=[];effects=[];zones=[];boss=null;}
function build(){clearObjects();if(world){scene.remove(world.group);world.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});}if(hero){disposeHero(hero);scene.remove(hero);}world=buildWorld(mapId,Math.floor(Math.random()*1e8));scene.add(world.group);scene.background=new T.Color(world.theme.fog);scene.fog=new T.FogExp2(world.theme.fog,.014);hero=actor(heroId,weaponFor(heroId,weaponIndex).id);scene.add(hero);player={...world.spawn,hp:120,maxHp:120,level:1,xp:0,pending:0,upgrades:{},attack:0,dash:0,dashTime:0,inv:0,hurt:0,angle:0,spell:{fire:3,ice:3,storm:3},distance:0};hero.position.set(player.x,0,player.z);camTarget.set(player.x,0,player.z);updateCamera(1);}
function renderChoices(){const box=$('#weapons');box.replaceChildren();for(let i=0;i<3;i++){const w=weaponFor(heroId,i),b=document.createElement('button');b.textContent=w.name;b.classList.toggle('selected',i===weaponIndex);b.onclick=()=>{weaponIndex=i;renderChoices();build();};box.append(b);}$('.menu-caption span').textContent=heroId==='silver'?'霜影 / SILVER VEIL':'游侠 / WOODLAND RANGER';}
for(const b of document.querySelectorAll('[data-hero]'))b.onclick=()=>{heroId=b.dataset.hero;weaponIndex=0;for(const q of document.querySelectorAll('[data-hero]'))q.classList.toggle('selected',q===b);renderChoices();build();};
for(const b of document.querySelectorAll('[data-map]'))b.onclick=()=>{mapId=b.dataset.map;for(const q of document.querySelectorAll('[data-map]'))q.classList.toggle('selected',q===b);build();};
function start(){unlockAudio();sound.reset(mapId);$('#audio-settings').open=false;keys.clear();releaseStick();build();time=0;kills=0;spawnTimer=1;waveTimer=32;bossBorn=false;state='playing';document.body.classList.add('playing');$('#menu').hidden=true;$('#hud').hidden=false;$('#touch').hidden=!touch;$('#dialog').close();$('#hero-name').textContent=heroId==='silver'?'霜影':'林地游侠';toast('寻找补给与祭坛 · 3 分钟后迎战林心守卫');}
$('#start').onclick=start;
function dialog(title,body,buttons=[]){const content=$('#dialog-content');content.innerHTML='<h2>'+title+'</h2><p>'+body+'</p>';const actions=document.createElement('div');actions.className='dialog-actions';for(const [text,fn]of buttons){const b=document.createElement('button');b.textContent=text;b.onclick=fn;actions.append(b);}content.append(actions);if(!$('#dialog').open)$('#dialog').showModal();}
function pause(){if(state==='playing'){state='paused';keys.clear();releaseStick();dialog('在林间歇一会儿','当前生命、技能与探索进度已保留。',[['继续远征',resume],['结束本局',()=>dialog('结束这次远征？','返回准备界面将结束当前对局。',[['返回暂停',()=>{state='playing';pause();}],['确认结束',menu]])]]);}else if(state==='paused')resume();}
function resume(){state='playing';$('#dialog').close();keys.clear();releaseStick();unlockAudio();}
function menu(){state='menu';$('#dialog').close();$('#menu').hidden=false;$('#hud').hidden=true;$('#touch').hidden=true;document.body.classList.remove('playing');keys.clear();releaseStick();build();}
$('#pause').onclick=pause;$('#dialog').addEventListener('cancel',e=>{e.preventDefault();if(state==='paused')resume();});
$('#sound').onclick=()=>{if(sound.ctx?.state==='running')sound.setMuted(!sound.muted);else sound.setMuted(false);unlockAudio();syncAudioUI();};
function upgrade(){if(player.pending<=0||state!=='playing')return;state='upgrade';keys.clear();releaseStick();const choices=chooseUpgrades(player);if(!choices.length){player.pending=0;state='playing';return;}dialog('灵光汇聚 · 选择成长','Lv.'+player.level+' · 火、冰、雷为独立法术，不改变武器属性');const cards=document.createElement('div');cards.className='cards';for(const u of choices){const b=document.createElement('button');b.innerHTML='<em>'+u.icon+'</em><strong>'+u.name+'</strong><small>'+u.text+'<br>当前 '+(player.upgrades[u.id]||0)+' / '+u.max+'</small>';b.onclick=()=>{player.upgrades[u.id]=(player.upgrades[u.id]||0)+1;if(u.id==='vitality'){player.maxHp+=24;player.hp=Math.min(player.maxHp,player.hp+24);}player.pending--;state='playing';$('#dialog').close();burst('heal',player.x,player.z,1.5);if(player.pending)upgrade();};cards.append(b);}$('#dialog-content').append(cards);}
function finish(win){state=win?'won':'lost';keys.clear();releaseStick();dialog(win?'林心重归宁静':'这一程，暂告段落',`${MAPS[mapId].name} · 存活 ${Math.floor(time/60)} 分 ${Math.floor(time%60)} 秒<br>击败 ${kills} · 等级 ${player.level} · 探索 ${world.sites.filter(s=>s.claimed).length}/2`,[['再次远征',start],['选择角色与地图',menu]]);}
function hitPlayer(n,x,z){if(player.inv>0||state!=='playing')return;player.hp=Math.max(0,player.hp-n);player.inv=.7;player.hurt=.35;shake=.16;$('#damage-edge').style.opacity=.7;effect('ring',player.x,player.z,0xff6861,1);sound.hurt();if(player.hp<=0)finish(false);}
function spawn(kind,x=null,z=null,site=null){if(enemies.filter(e=>e.alive).length>=60)return null;if(x===null){for(let i=0;i<25;i++){const a=Math.random()*Math.PI*2,d=19+Math.random()*7;const nx=player.x+Math.cos(a)*d,nz=player.z+Math.sin(a)*d;if(clearAt(world,nx,nz,1)){x=nx;z=nz;break;}}}if(x===null||!clearAt(world,x,z,.65))return null;const cfg=ENEMIES[kind],e={...cfg,x,z,kind,id:++enemyId,alive:true,hp:cfg.hp*(1+Math.min(time,300)*.003),maxHp:cfg.hp*(1+Math.min(time,300)*.003),cool:1+Math.random(),wind:0,hurt:0,slow:0,site};e.mesh=actor(kind);e.mesh.position.set(x,0,z);scene.add(e.mesh);enemies.push(e);return e;}
function hurtEnemy(e,n){if(!e.alive)return;e.hp-=n*(e===boss&&e.recover>0?1.25:1);e.hurt=.12;if(e.hp<=0){e.alive=false;kills++;scene.remove(e.mesh);effect('ring',e.x,e.z,0xd9d5aa,.6);if(e===boss){finish(true);return;}const o={x:e.x,z:e.z,mesh:mesh('OctahedronGeometry',[.22],0x76f0ef,e.x,.5,e.z,null,true),xp:e.xp};o.mesh.add(glow(0x61e6ed,2.2));scene.add(o.mesh);orbs.push(o);}}
function shoot(){const w=weaponFor(heroId,weaponIndex),targets=enemies.filter(e=>e.alive);if(boss?.alive)targets.push(boss);let nearest=null,d=w.range;for(const e of targets){const n=Math.hypot(e.x-player.x,e.z-player.z);if(n<d){nearest=e;d=n;}}if(!nearest)return;const angle=Math.atan2(nearest.x-player.x,nearest.z-player.z);player.angle=angle;player.attack=1/(w.rate*(1+.15*(player.upgrades.haste||0)));hero.userData.shoot=.16;for(let i=0;i<w.count;i++){const a=angle+(i-(w.count-1)/2)*.14,color=w.color;let m;if(w.id==='shuriken'){m=new T.Group();for(let j=0;j<4;j++){const blade=mesh('BoxGeometry',[.08,.06,.75],color,0,0,0,m,true);blade.rotation.y=j*Math.PI/4;}}else m=mesh('SphereGeometry',[w.id==='fire'?.23:w.id==='dark'?.26:.075,8,6],color,0,0,0,null,true);if(['fire','dark'].includes(w.id))m.add(glow(color,2.5));m.position.set(player.x,1.15,player.z);scene.add(m);bullets.push({mesh:m,x:player.x,z:player.z,vx:Math.sin(a)*w.speed,vz:Math.cos(a)*w.speed,life:w.range/w.speed,damage:w.damage*(1+.18*(player.upgrades.power||0)),kind:w.id,hits:new Set(),pierce:w.id==='shuriken'?2:1,target:nearest});}effect('spark',player.x+Math.sin(angle)*.65,player.z+Math.cos(angle)*.65,w.color,.14,1.3);sound.shot(w.id);}
function dash(){if(state!=='playing'||player.dash>0)return;const input=movement(),angle=Math.hypot(input.x,input.z)>.1?Math.atan2((input.x+input.z)*.7071,(input.z-input.x)*.7071):player.angle;player.dash=2.3/(1+.12*(player.upgrades.stride||0));player.inv=.32;player.dashTime=.24;player.dashAngle=angle;if(heroId==='silver'){const ox=player.x,oz=player.z;for(let d=5.5;d>0;d-=.2){const x=ox+Math.sin(angle)*d,z=oz+Math.cos(angle)*d;if(clearAt(world,x,z,.45)){player.x=x;player.z=z;break;}}burst('dark',ox,oz,1.3);burst('dark',player.x,player.z,1.5);}else effect('ring',player.x,player.z,0xdac48d,1);sound.dodge(heroId==='silver');}
function movement(){let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+stick.x,z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+stick.z;const d=Math.hypot(x,z);if(d>1){x/=d;z/=d;}return{x,z};}
function addZone(x,z,r,delay,damage,kind='poison'){const ring=mesh('TorusGeometry',[r,.07,4,40],kind==='meteor'?0xfbd9a0:kind==='boss'?0xff876b:0xee9be4,x,.09,z,null,true);ring.rotation.x=-Math.PI/2;scene.add(ring);zones.push({x,z,r,delay,life:delay+(kind==='boss'?.15:2),damage,kind,mesh:ring});}
function updateEnemies(dt){for(const e of enemies){if(!e.alive)continue;e.cool-=dt;e.hurt=Math.max(0,e.hurt-dt);e.slow=Math.max(0,e.slow-dt);const dx=player.x-e.x,dz=player.z-e.z,d=Math.hypot(dx,dz),a=Math.atan2(dx,dz);e.mesh.rotation.y=a;let moving=0;
 if(e.wind>0){e.wind-=dt;if(e.wind<=0){if(e.kind==='spitter'){addZone(e.tx,e.tz,2,1.1,13);sound.tone(220,.15,.06,'sine',80);}else if(e.kind==='shaman'){for(const ally of enemies)if(ally.alive&&Math.hypot(ally.x-e.x,ally.z-e.z)<6)ally.hp=Math.min(ally.maxHp,ally.hp+ally.maxHp*.1);burst('heal',e.x,e.z,3);}else{if(Math.hypot(player.x-e.tx,player.z-e.tz)<e.size+1.1)hitPlayer(e.damage,e.x,e.z);burst('fire',e.tx,e.tz,.8);}e.cool=e.kind==='spitter'?3:1.3;}}
 else if(e.cool<=0&&d<(e.kind==='spitter'?15:e.kind==='shaman'?12:e.kind==='wolf'?3:1.4+e.size)){e.wind=e.kind==='spitter'?.75:.6;e.tx=player.x;e.tz=player.z;effect('ring',e.x,e.z,0xffab71,e.size+1);}
 else{let tx=player.x,tz=player.z;if(['spitter','shaman'].includes(e.kind)){const tank=enemies.find(q=>q.alive&&q.kind==='golem'&&Math.hypot(q.x-e.x,q.z-e.z)<8);if(tank){const ta=Math.atan2(tank.x-player.x,tank.z-player.z);tx=tank.x+Math.sin(ta)*3;tz=tank.z+Math.cos(ta)*3;}else if(d<10){tx=e.x;tz=e.z;}}
 const ta=Math.atan2(tx-e.x,tz-e.z),speed=e.speed*(e.slow>0?.45:1)*(world.patches.some(p=>Math.hypot(p.x-e.x,p.z-e.z)<p.r)?.75:1),step=speed*dt;if(Math.hypot(tx-e.x,tz-e.z)>.4){const ox=e.x,oz=e.z;moveActor(world,e,Math.sin(ta)*step,Math.cos(ta)*step,e.size*.6);if(Math.hypot(e.x-ox,e.z-oz)<step*.2)moveActor(world,e,Math.sin(ta+1.3)*step,Math.cos(ta+1.3)*step,e.size*.6);moving=speed;}}
 e.mesh.position.set(e.x,0,e.z);animateActor(e.mesh,time+e.id,moving,e.wind,e.hurt);if(e.wind>0)e.mesh.userData.rig.scale.setScalar(1+Math.sin(e.wind*15)*.04);
 }enemies=enemies.filter(e=>e.alive);}
function spawnBoss(){bossBorn=true;const m=actor('boss'),a=Math.random()*6.28;boss={x:player.x+Math.sin(a)*14,z:player.z+Math.cos(a)*14,hp:1900,maxHp:1900,size:2,alive:true,mesh:m,cool:3,wind:0,recover:0,kind:'boss',phase:1,turn:0};boss.x=Math.max(-56,Math.min(56,boss.x));boss.z=Math.max(-56,Math.min(56,boss.z));m.position.set(boss.x,0,boss.z);scene.add(m);toast('林心守卫苏醒 · 躲开蓄力，抓住破绽');burst('fire',boss.x,boss.z,4);}
function updateBoss(dt){if(!boss?.alive)return;const b=boss;b.hurt=Math.max(0,(b.hurt||0)-dt);b.cool-=dt;const a=Math.atan2(player.x-b.x,player.z-b.z);b.mesh.rotation.y=a;if(b.hp<b.maxHp*.5&&b.phase===1){b.phase=2;toast('守卫狂暴 · 三重裂地！');}
 if(b.aoeWait>0){b.aoeWait-=dt;if(b.aoeWait<=0){b.recover=1.5;toast('裂地结束 · 趁破绽反击');}}
 else if(b.recover>0)b.recover-=dt;
 else if(b.charge>0){const ox=b.x,oz=b.z;b.x+=Math.sin(b.angle)*18*dt;b.z+=Math.cos(b.angle)*18*dt;b.x=Math.max(-60,Math.min(60,b.x));b.z=Math.max(-60,Math.min(60,b.z));if(segmentDistance(player.x,player.z,ox,oz,b.x,b.z)<2.2)hitPlayer(30,b.x,b.z);b.charge-=dt;if(b.charge<=0){b.recover=1.7;b.cool=3;toast('守卫露出破绽 · 伤害提高 25%');}}
 else if(b.wind>0){b.wind-=dt;if(b.wind<=0){b.charge=.7;}}
 else if(b.cool<=0){b.turn++;if(b.turn%2){b.wind=1.2;b.angle=a;for(let i=1;i<=7;i++){effect('ring',b.x+Math.sin(a)*i*1.7,b.z+Math.cos(a)*i*1.7,0xffc18c,.6);if(effects.length){effects[effects.length-1].life=1.2;effects[effects.length-1].max=1.2;}}toast('守卫冲撞 · 向侧面闪避');}else{for(const offset of b.phase===2?[-4,0,4]:[0])addZone(player.x+Math.cos(a)*offset,player.z-Math.sin(a)*offset,b.phase===2?2.3:3,1.5,27,'boss');b.aoeWait=1.5;b.cool=5;}}
 else{moveActor(world,b,Math.sin(a)*1.8*dt,Math.cos(a)*1.8*dt,1.5);}
 b.mesh.position.set(b.x,0,b.z);animateActor(b.mesh,time,b.recover>0?0:2,b.wind,b.hurt);}
function updateSites(dt){for(const s of world.sites){if(s.crystal){s.crystal.rotation.y+=dt;s.crystal.position.y=1.1+Math.sin(time*2)*.12;}s.ring.rotation.z+=dt*.3;const d=Math.hypot(player.x-s.x,player.z-s.z);if(s.claimed)continue;if(!s.state&&d<6){s.state='warning';s.timer=2;toast(s.type==='altar'?'远古祭坛 · 精锐守卫即将苏醒':'猎人补给 · 清理守卫领取治疗');}if(s.state==='warning'){s.timer-=dt;if(s.timer<=0){s.state='guarded';s.guards=[];for(let i=0;i<4;i++){const a=i*Math.PI/2,e=spawn(i===0?'golem':i===1?'spitter':'wolf',s.x+Math.sin(a)*4,s.z+Math.cos(a)*4,s);if(e)s.guards.push(e);}}}if(s.state==='guarded'&&s.guards.every(e=>!e.alive)){s.state='ready';toast('守卫已清除 · 靠近领取奖励');}if(s.state==='ready'&&d<2.5){s.claimed=true;s.ring.visible=false;burst('heal',s.x,s.z,3);if(s.type==='altar'){player.pending++;toast('祭坛祝福 · 获得一项技能');}else{player.hp=Math.min(player.maxHp,player.hp+player.maxHp*.4);for(const o of orbs)o.attract=true;toast('补给已领取 · 治疗 40%，吸引所有灵光');}}}}
function update(dt){time+=dt;simTimer+=dt;player.xpFlash=Math.max(0,(player.xpFlash||0)-dt);player.attack-=dt;player.dash=Math.max(0,player.dash-dt);player.inv=Math.max(0,player.inv-dt);player.hurt=Math.max(0,player.hurt-dt);player.dashTime=Math.max(0,player.dashTime-dt);const input=movement(),moving=Math.hypot(input.x,input.z),slow=world.patches.some(p=>Math.hypot(player.x-p.x,player.z-p.z)<p.r)?.72:1,speed=6.5*(1+.08*(player.upgrades.stride||0))*slow;
 // Camera-oriented input keeps up/down aligned with the screen.
 const dx=(input.x+input.z)*.7071,dz=(input.z-input.x)*.7071;moveActor(world,player,dx*speed*dt,dz*speed*dt);if(moving>.1&&player.attack>.12)player.angle=Math.atan2(dx,dz);if(heroId==='scout'&&player.dashTime>0)moveActor(world,player,Math.sin(player.dashAngle)*22*dt,Math.cos(player.dashAngle)*22*dt);hero.position.set(player.x,heroId==='scout'&&player.dashTime>0?.2:0,player.z);hero.rotation.y=player.angle;hero.userData.dashTime=player.dashTime;hero.userData.rig.rotation.x=!hero.userData.skinned&&heroId==='scout'&&player.dashTime>0?(1-player.dashTime/.24)*Math.PI*2:0;hero.userData.shoot=Math.max(0,(hero.userData.shoot||0)-dt);animateActor(hero,time,moving*speed,hero.userData.shoot,player.hurt);if(heroId==='silver'&&player.dashTime>0)hero.scale.setScalar(.65+.35*(1-player.dashTime/.24));else hero.scale.setScalar(1);
 if(player.attack<=0&&player.dashTime===0)shoot();spawnTimer-=dt;if(spawnTimer<=0){spawnTimer=Math.max(.65,2-time*.007);const kinds=time<25?['mushroom']:time<55?['mushroom','wolf']:['mushroom','wolf','golem','spitter','shaman'];spawn(kinds[Math.floor(Math.random()*kinds.length)]);}if(time>=waveTimer){waveTimer=time+30;toast('兽群从四周接近 · 留意突围路线');for(let i=0;i<6;i++){const a=i/6*Math.PI*1.7,r=17;spawn(i%3===0?'golem':'wolf',player.x+Math.sin(a)*r,player.z+Math.cos(a)*r);}}
 updateEnemies(dt);if(state!=='playing')return;updateBoss(dt);if(state!=='playing')return;
 const targets=()=>[...enemies,...(boss?.alive?[boss]:[])];
 for(const b of bullets){const ox=b.x,oz=b.z;if(b.kind==='dark'&&b.target?.alive){const a=Math.atan2(b.target.x-b.x,b.target.z-b.z);b.vx=T.MathUtils.lerp(b.vx,Math.sin(a)*12,.06);b.vz=T.MathUtils.lerp(b.vz,Math.cos(a)*12,.06);}b.x+=b.vx*dt;b.z+=b.vz*dt;b.life-=dt;b.mesh.position.set(b.x,1.15,b.z);if(b.kind==='shuriken')b.mesh.rotation.y+=dt*24;if(!clearAt(world,b.x,b.z,.1))b.life=0;
 for(const e of targets()){if(!e.alive||b.hits.has(e.id??'boss')||b.life<=0)continue;if(segmentDistance(e.x,e.z,ox,oz,b.x,b.z)<e.size+.2){b.hits.add(e.id??'boss');hurtEnemy(e,b.damage);sound.impact(b.kind);effect('spark',e.x,e.z,0xffdf97,.13,1);if(['fire','dark'].includes(b.kind)){const radius=b.kind==='fire'?2.5:2;burst(b.kind,e.x,e.z,radius);for(const other of targets())if(other!==e&&Math.hypot(other.x-e.x,other.z-e.z)<radius)hurtEnemy(other,b.damage*.65);}b.pierce--;if(b.pierce<=0)b.life=0;}}
 }bullets=bullets.filter(b=>{if(b.life>0)return true;scene.remove(b.mesh);return false;});if(state!=='playing')return;
 for(const z of zones){z.delay-=dt;z.life-=dt;z.mesh.scale.setScalar(1+Math.sin(time*8)*.015);if(z.delay<=0){z.mesh.material=mat(z.kind==='meteor'?0xffbc63:z.kind==='boss'?0xff6b48:0xaa60cc,true);if(!z.burst){z.burst=true;burst(['boss','meteor'].includes(z.kind)?'fire':'dark',z.x,z.z,z.r);if(z.kind==='meteor')for(const e of targets())if(Math.hypot(e.x-z.x,e.z-z.z)<z.r)hurtEnemy(e,z.damage);}if(z.kind!=='meteor'&&Math.hypot(player.x-z.x,player.z-z.z)<z.r+.4)hitPlayer(z.damage,z.x,z.z);}}
 zones=zones.filter(z=>{if(z.life>0)return true;scene.remove(z.mesh);return false;});if(state!=='playing')return;
 for(const id of ['fire','ice','storm']){const rank=player.upgrades[id]||0;if(!rank)continue;player.spell[id]-=dt;if(player.spell[id]>0)continue;const near=targets().filter(e=>e.alive&&Math.hypot(e.x-player.x,e.z-player.z)<17).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z));if(!near.length)continue;player.spell[id]=id==='ice'?7:5.5;if(id==='fire'){const e=near[0];addZone(e.x,e.z,3.5,.5,35*rank,'meteor');zones[zones.length-1].life=.65;effect('meteor',e.x,e.z,0xffbd66,.8,6);}else if(id==='ice'){burst('ice',player.x,player.z,5);for(const e of near)if(Math.hypot(e.x-player.x,e.z-player.z)<5){hurtEnemy(e,20*rank);e.slow=2;}}else{let x=player.x,z=player.z;for(const e of near.slice(0,2+rank)){lightning(x,z,e.x,e.z);hurtEnemy(e,27*rank);x=e.x;z=e.z;}}}
 if(state!=='playing')return;
 for(const o of orbs){const d=Math.hypot(o.x-player.x,o.z-player.z);if(d<3+(player.upgrades.magnet||0)*2||o.attract){o.attract=true;const a=Math.atan2(player.x-o.x,player.z-o.z),s=Math.min(d,dt*15);o.x+=Math.sin(a)*s;o.z+=Math.cos(a)*s;}o.mesh.position.set(o.x,.45+Math.sin(time*3)*.08,o.z);o.mesh.rotation.y+=dt*2;if(d<.6){collectExperience(o.xp);o.dead=true;scene.remove(o.mesh);}}
 orbs=orbs.filter(o=>!o.dead);if(orbs.length>350){const dropped=orbs.splice(0,orbs.length-350);for(const o of dropped)scene.remove(o.mesh);}updateSites(dt);if(time>=180&&!bossBorn)spawnBoss();if(player.pending)upgrade();}
function collectExperience(n){const previous=player.level;player.xpGain=(player.xpFlash>0?player.xpGain:0)+n;player.xpFlash=.9;grantExperience(player,n);if(player.level>previous){sound.level();effect('ring',player.x,player.z,0x8ef9ff,2.2);toast('升级至 Lv.'+player.level+' · 选择新的力量');}else sound.pickup();}
function updateEffects(dt){for(const e of effects){e.life-=dt;const p=1-e.life/e.max;if(e.kind==='line')continue;const scale=e.kind==='ring'?e.r*(.4+p*.8):e.kind==='spike'?e.r*Math.sin(Math.PI*Math.min(.99,p)):e.r*(1-p*.7);e.mesh.scale.setScalar(Math.max(.001,scale));if(e.vy)e.mesh.position.y+=dt*e.vy;}effects=effects.filter(e=>{if(e.life>0)return true;scene.remove(e.mesh);if(e.kind==='line'){e.mesh.geometry.dispose();e.mesh.material.dispose();}return false;});}
function updateCamera(dt){const menuMode=state==='menu',target=new T.Vector3(player.x+(menuMode?-2:0),menuMode?1.1:.5,player.z+(menuMode?2:0));camTarget.lerp(target,1-Math.exp(-dt*8));const distance=menuMode?8.5:touch&&innerHeight>innerWidth?27:touch?20:24;camera.position.set(camTarget.x+distance*.7,camTarget.y+distance*(menuMode?.48:1),camTarget.z+distance*.7);if(shake>0){camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake;}camera.lookAt(camTarget);sun.position.set(player.x+15,30,player.z+12);sun.target.position.set(player.x,0,player.z);}
function updateHUD(){const ratio=player.hp/player.maxHp;$('#level').textContent='Lv.'+player.level;$('.hp i').style.width=ratio*100+'%';$('.hp i').style.background=ratio<.3?'#e56b65':'';$('.hp b').textContent=Math.ceil(player.hp)+' / '+player.maxHp;const needed=experienceNeeded(player.level);$('.xp i').style.width=player.xp/needed*100+'%';$('.xp').setAttribute('aria-valuenow',player.xp);$('.xp').setAttribute('aria-valuemax',needed);$('#xp-value').textContent=player.xp+' / '+needed;$('#xp-next').textContent='→ Lv.'+(player.level+1);$('.status').classList.toggle('gaining',player.xpFlash>0);$('#xp-gain').textContent=player.xpFlash>0?'+'+player.xpGain+' 经验':'';$('#timer').textContent=String(Math.floor(time/60)).padStart(2,'0')+':'+String(Math.floor(time%60)).padStart(2,'0');$('#kills').textContent='击败 '+kills;$('#boss-hud').hidden=!boss?.alive;if(boss?.alive){$('#boss-hud i').style.width=Math.max(0,boss.hp/boss.maxHp)*100+'%';$('#boss-hud span').textContent=boss.recover>0?'破绽 · 伤害 +25%':'林心守卫 · '+(boss.phase===2?'狂暴':'觉醒');}$('#objective').textContent=boss?.alive?'击败林心守卫，完成远征':time<20?'探索地图上的补给与祭坛':'守卫苏醒倒计时 '+Math.max(0,Math.ceil(180-time))+' 秒 · 探索 '+world.sites.filter(s=>s.claimed).length+'/2';$('#hint').textContent=ratio<.3?'生命危险 · 闪避并寻找补给':weaponFor(heroId,weaponIndex).name+' · '+(world.patches.some(p=>Math.hypot(p.x-player.x,p.z-player.z)<p.r)?MAPS[mapId].slow+'减速':'移动迎战');$('#dash').textContent=player.dash>0?player.dash.toFixed(1)+'s':heroId==='silver'?'瞬移':'翻滚';$('#skills').innerHTML=Object.entries(player.upgrades).map(([id,n])=>'<span>'+({power:'锋芒',haste:'疾风',fire:'陨火',ice:'冰环',storm:'落雷',vitality:'坚韧',stride:'步伐',magnet:'牵引'}[id])+' '+n+'</span>').join('');$('#damage-edge').style.opacity=player.hurt>0?.6:ratio<.3?.16+Math.sin(time*4)*.05:0;
 const c=$('#map canvas').getContext('2d');c.fillStyle='#193d36';c.fillRect(0,0,144,144);c.strokeStyle='#43664e';c.strokeRect(6,6,132,132);c.fillStyle='#72947a';for(const o of world.obstacles)c.fillRect(72+o.x,72+o.z,1.5,1.5);for(const s of world.sites){c.fillStyle=s.claimed?'#608371':s.type==='altar'?'#ceb3ff':'#f0d694';c.beginPath();c.arc(72+s.x,72+s.z,4,0,Math.PI*2);c.fill();c.font='10px sans-serif';c.textAlign='center';c.fillText(s.type==='altar'?'技能':'治疗',72+s.x,64+s.z);}c.fillStyle='#e78275';for(const e of enemies)if(e.alive)c.fillRect(72+e.x,72+e.z,2,2);if(boss?.alive){c.fillStyle='#ffb070';c.fillRect(69+boss.x,69+boss.z,6,6);}c.fillStyle='#fff9d6';c.beginPath();c.arc(72+player.x,72+player.z,3,0,Math.PI*2);c.fill();}
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLElement&&e.target.closest('input,select,textarea,[contenteditable="true"]'))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','escape'].includes(k))e.preventDefault();if(k==='escape'){pause();return;}if(k==='shift'||k===' '){dash();return;}if(state==='playing')keys.add(k);});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function releaseStick(){stick.x=stick.z=0;stick.id=null;$('#joystick i').style.transform='';}
function moveStick(e){if(state!=='playing')return;const r=$('#joystick').getBoundingClientRect(),x=e.clientX-r.x-r.width/2,z=e.clientY-r.y-r.height/2,d=Math.hypot(x,z),f=Math.min(1,34/(d||1));stick.x=x*f/34;stick.z=z*f/34;$('#joystick i').style.transform=`translate(${x*f}px,${z*f}px)`;}
$('#joystick').addEventListener('pointerdown',e=>{if(state!=='playing')return;e.preventDefault();stick.id=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);moveStick(e);});$('#joystick').addEventListener('pointermove',e=>{if(stick.id===e.pointerId)moveStick(e);});for(const name of ['pointerup','pointercancel','lostpointercapture'])$('#joystick').addEventListener(name,releaseStick);$('#dash').addEventListener('pointerdown',e=>{e.preventDefault();dash();});
window.addEventListener('blur',()=>{keys.clear();releaseStick();if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();releaseStick();});renderer.setSize(innerWidth,innerHeight,false);
renderChoices();
for(const b of document.querySelectorAll('#menu button'))b.disabled=true;
try{await loadHeroAssets((n,total)=>{$('#asset-loading span').textContent='正在准备人物与动作 · '+n+' / '+total;});$('#asset-loading').hidden=true;for(const b of document.querySelectorAll('#menu button'))b.disabled=false;build();}
catch(e){$('#asset-loading span').textContent='角色资源加载失败，请检查网络后重试。';$('#asset-retry').hidden=false;$('#asset-retry').onclick=()=>location.reload();throw e;}
function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;sound.update(dt,{map:mapId,mode:state,boss:!!boss?.alive,pressure:Math.min(1,enemies.filter(e=>e.alive&&Math.hypot(e.x-player.x,e.z-player.z)<12).length/10)});if(state==='playing'){update(dt);updateEffects(dt);}else if(state==='menu'){animateActor(hero,now/1000,.3);hero.rotation.y=.65+Math.sin(now/3000)*.2;world.light.intensity=9+Math.sin(now/100)*1.5;}for(let i=0;i<world.motes.length;i++){const m=world.motes[i];m.position.y+=Math.sin(now/1200+i)*dt*.15;m.scale.setScalar(.5+Math.sin(now/550+i)*.3);}world.fire.scale.y=1+Math.sin(now/90)*.3;
 if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('#toast').style.opacity=0;}shake=Math.max(0,shake-dt);updateCamera(dt);uiTime+=dt;if(uiTime>.1&&state!=='menu'){uiTime=0;updateHUD();}renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.game3d={get audio(){return sound;},get hero(){return hero;},get state(){return state;},get player(){return player;},get enemies(){return enemies;},get boss(){return boss;},get world(){return world;},get time(){return time;},get renderer(){return renderer;},start,pause,resume,menu,dash,spawn,spawnBoss,step(dt){if(state==='playing')update(dt);},grant(n){collectExperience(n);upgrade();},damage:hitPlayer,hurtEnemy,select(hero,map,index){heroId=hero;mapId=map;weaponIndex=index;renderChoices();build();}};
