// Generated by scripts/build-material-sfx.py. See docs/audio-material-sources.json.
export const SFX_FILE = 'assets/audio/material-sfx.mp3';
export const SFX_CUES = {
  "rifle:shot": [
    {
      "offset": 0.12,
      "duration": 0.32,
      "gain": 1
    },
    {
      "offset": 0.56,
      "duration": 0.32,
      "gain": 1
    }
  ],
  "rifle:impact": [
    {
      "offset": 1.0,
      "duration": 0.23,
      "gain": 1
    },
    {
      "offset": 1.35,
      "duration": 0.23,
      "gain": 1
    }
  ],
  "rifle:mechanism": [
    {
      "offset": 1.7,
      "duration": 0.24,
      "gain": 1
    },
    {
      "offset": 2.06,
      "duration": 0.24,
      "gain": 1
    }
  ],
  "shotgun:shot": [
    {
      "offset": 2.42,
      "duration": 0.52,
      "gain": 1
    },
    {
      "offset": 3.06,
      "duration": 0.52,
      "gain": 1
    }
  ],
  "shotgun:impact": [
    {
      "offset": 3.7,
      "duration": 0.33,
      "gain": 1
    },
    {
      "offset": 4.15,
      "duration": 0.33,
      "gain": 1
    }
  ],
  "shotgun:mechanism": [
    {
      "offset": 4.6,
      "duration": 0.35,
      "gain": 1
    },
    {
      "offset": 5.07,
      "duration": 0.35,
      "gain": 1
    }
  ],
  "crossbow:shot": [
    {
      "offset": 5.54,
      "duration": 0.35,
      "gain": 1
    },
    {
      "offset": 6.01,
      "duration": 0.35,
      "gain": 1
    }
  ],
  "crossbow:impact": [
    {
      "offset": 6.48,
      "duration": 0.25,
      "gain": 1
    },
    {
      "offset": 6.85,
      "duration": 0.25,
      "gain": 1
    }
  ],
  "crossbow:mechanism": [
    {
      "offset": 7.22,
      "duration": 0.31,
      "gain": 1
    },
    {
      "offset": 7.65,
      "duration": 0.31,
      "gain": 1
    }
  ],
  "shuriken:shot": [
    {
      "offset": 8.08,
      "duration": 0.28,
      "gain": 1
    },
    {
      "offset": 8.48,
      "duration": 0.28,
      "gain": 1
    }
  ],
  "shuriken:impact": [
    {
      "offset": 8.88,
      "duration": 0.29,
      "gain": 1
    },
    {
      "offset": 9.29,
      "duration": 0.29,
      "gain": 1
    }
  ],
  "shuriken:mechanism": [
    {
      "offset": 9.7,
      "duration": 0.22,
      "gain": 1
    },
    {
      "offset": 10.04,
      "duration": 0.22,
      "gain": 1
    }
  ],
  "fire:shot": [
    {
      "offset": 10.38,
      "duration": 0.52,
      "gain": 1
    },
    {
      "offset": 11.02,
      "duration": 0.52,
      "gain": 1
    }
  ],
  "fire:impact": [
    {
      "offset": 11.66,
      "duration": 0.43,
      "gain": 1
    },
    {
      "offset": 12.21,
      "duration": 0.43,
      "gain": 1
    }
  ],
  "fire:mechanism": [
    {
      "offset": 12.76,
      "duration": 0.3,
      "gain": 1
    },
    {
      "offset": 13.18,
      "duration": 0.3,
      "gain": 1
    }
  ],
  "dark:shot": [
    {
      "offset": 13.6,
      "duration": 0.49,
      "gain": 1
    },
    {
      "offset": 14.21,
      "duration": 0.49,
      "gain": 1
    }
  ],
  "dark:impact": [
    {
      "offset": 14.82,
      "duration": 0.43,
      "gain": 1
    },
    {
      "offset": 15.37,
      "duration": 0.43,
      "gain": 1
    }
  ],
  "dark:mechanism": [
    {
      "offset": 15.92,
      "duration": 0.35,
      "gain": 1
    },
    {
      "offset": 16.39,
      "duration": 0.35,
      "gain": 1
    }
  ],
  "shade:shot": [
    {
      "offset": 16.86,
      "duration": 0.39,
      "gain": 1
    },
    {
      "offset": 17.37,
      "duration": 0.39,
      "gain": 1
    }
  ],
  "shade:impact": [
    {
      "offset": 17.88,
      "duration": 0.37,
      "gain": 1
    },
    {
      "offset": 18.37,
      "duration": 0.37,
      "gain": 1
    }
  ],
  "shade:mechanism": [
    {
      "offset": 18.86,
      "duration": 0.29,
      "gain": 1
    },
    {
      "offset": 19.27,
      "duration": 0.29,
      "gain": 1
    }
  ],
  "shadowblade:shot": [
    {
      "offset": 19.68,
      "duration": 0.36,
      "gain": 1
    },
    {
      "offset": 20.16,
      "duration": 0.36,
      "gain": 1
    }
  ],
  "shadowblade:impact": [
    {
      "offset": 20.64,
      "duration": 0.34,
      "gain": 1
    },
    {
      "offset": 21.1,
      "duration": 0.34,
      "gain": 1
    }
  ],
  "shadowblade:mechanism": [
    {
      "offset": 21.56,
      "duration": 0.26,
      "gain": 1
    },
    {
      "offset": 21.94,
      "duration": 0.26,
      "gain": 1
    }
  ],
  "grimoire:shot": [
    {
      "offset": 22.32,
      "duration": 0.4,
      "gain": 1
    },
    {
      "offset": 22.84,
      "duration": 0.4,
      "gain": 1
    }
  ],
  "grimoire:impact": [
    {
      "offset": 23.36,
      "duration": 0.37,
      "gain": 1
    },
    {
      "offset": 23.85,
      "duration": 0.37,
      "gain": 1
    }
  ],
  "grimoire:mechanism": [
    {
      "offset": 24.34,
      "duration": 0.33,
      "gain": 1
    },
    {
      "offset": 24.79,
      "duration": 0.33,
      "gain": 1
    }
  ],
  "harpoon:shot": [
    {
      "offset": 25.24,
      "duration": 0.36,
      "gain": 1
    },
    {
      "offset": 25.72,
      "duration": 0.36,
      "gain": 1
    }
  ],
  "harpoon:impact": [
    {
      "offset": 26.2,
      "duration": 0.4,
      "gain": 1
    },
    {
      "offset": 26.72,
      "duration": 0.4,
      "gain": 1
    }
  ],
  "harpoon:mechanism": [
    {
      "offset": 27.24,
      "duration": 0.3,
      "gain": 1
    },
    {
      "offset": 27.66,
      "duration": 0.3,
      "gain": 1
    }
  ],
  "harpoon:shot:1": [
    {
      "offset": 28.08,
      "duration": 0.43,
      "gain": 1
    },
    {
      "offset": 28.63,
      "duration": 0.43,
      "gain": 1
    }
  ],
  "harpoon:shot:2": [
    {
      "offset": 29.18,
      "duration": 0.55,
      "gain": 1
    },
    {
      "offset": 29.85,
      "duration": 0.55,
      "gain": 1
    }
  ],
  "harpoon:impact:1": [
    {
      "offset": 30.52,
      "duration": 0.45,
      "gain": 1
    },
    {
      "offset": 31.09,
      "duration": 0.45,
      "gain": 1
    }
  ],
  "harpoon:impact:2": [
    {
      "offset": 31.66,
      "duration": 0.55,
      "gain": 1
    },
    {
      "offset": 32.33,
      "duration": 0.55,
      "gain": 1
    }
  ],
  "boomerang:shot": [
    {
      "offset": 33.0,
      "duration": 0.42,
      "gain": 1
    },
    {
      "offset": 33.54,
      "duration": 0.42,
      "gain": 1
    }
  ],
  "boomerang:impact": [
    {
      "offset": 34.08,
      "duration": 0.27,
      "gain": 1
    },
    {
      "offset": 34.47,
      "duration": 0.27,
      "gain": 1
    }
  ],
  "boomerang:mechanism": [
    {
      "offset": 34.86,
      "duration": 0.31,
      "gain": 1
    },
    {
      "offset": 35.29,
      "duration": 0.31,
      "gain": 1
    }
  ],
  "boomerang:mechanism:1": [
    {
      "offset": 35.72,
      "duration": 0.26,
      "gain": 1
    },
    {
      "offset": 36.1,
      "duration": 0.26,
      "gain": 1
    }
  ],
  "sporelantern:shot": [
    {
      "offset": 36.48,
      "duration": 0.37,
      "gain": 1
    },
    {
      "offset": 36.97,
      "duration": 0.37,
      "gain": 1
    }
  ],
  "sporelantern:impact": [
    {
      "offset": 37.46,
      "duration": 0.42,
      "gain": 1
    },
    {
      "offset": 38.0,
      "duration": 0.42,
      "gain": 1
    }
  ],
  "sporelantern:mechanism": [
    {
      "offset": 38.54,
      "duration": 0.22,
      "gain": 1
    },
    {
      "offset": 38.88,
      "duration": 0.22,
      "gain": 1
    }
  ],
  "sporelantern:move": [
    {
      "offset": 39.22,
      "duration": 0.24,
      "gain": 1
    },
    {
      "offset": 39.58,
      "duration": 0.24,
      "gain": 1
    }
  ],
  "sporelantern:burst": [
    {
      "offset": 39.94,
      "duration": 0.64,
      "gain": 1
    },
    {
      "offset": 40.7,
      "duration": 0.64,
      "gain": 1
    }
  ],
  "sporelantern:shield": [
    {
      "offset": 41.46,
      "duration": 0.56,
      "gain": 1
    },
    {
      "offset": 42.14,
      "duration": 0.56,
      "gain": 1
    }
  ],
  "miasmalantern:shot": [
    {
      "offset": 42.82,
      "duration": 0.47,
      "gain": 1
    },
    {
      "offset": 43.41,
      "duration": 0.47,
      "gain": 1
    }
  ],
  "miasmalantern:impact": [
    {
      "offset": 44.0,
      "duration": 0.51,
      "gain": 1
    },
    {
      "offset": 44.63,
      "duration": 0.51,
      "gain": 1
    }
  ],
  "miasmalantern:charge": [
    {
      "offset": 45.26,
      "duration": 0.18,
      "gain": 1
    },
    {
      "offset": 45.56,
      "duration": 0.18,
      "gain": 1
    }
  ],
  "spell:ice": [
    {
      "offset": 45.86,
      "duration": 0.67,
      "gain": 1
    },
    {
      "offset": 46.65,
      "duration": 0.67,
      "gain": 1
    }
  ],
  "spell:storm": [
    {
      "offset": 47.44,
      "duration": 0.69,
      "gain": 1
    },
    {
      "offset": 48.25,
      "duration": 0.69,
      "gain": 1
    }
  ],
  "spell:fire": [
    {
      "offset": 49.06,
      "duration": 0.72,
      "gain": 1
    },
    {
      "offset": 49.9,
      "duration": 0.72,
      "gain": 1
    }
  ],
  "spell:veil": [
    {
      "offset": 50.74,
      "duration": 0.64,
      "gain": 1
    },
    {
      "offset": 51.5,
      "duration": 0.64,
      "gain": 1
    }
  ],
  "spell:chain": [
    {
      "offset": 52.26,
      "duration": 0.72,
      "gain": 1
    },
    {
      "offset": 53.1,
      "duration": 0.72,
      "gain": 1
    }
  ],
  "spell:rift": [
    {
      "offset": 53.94,
      "duration": 0.78,
      "gain": 1
    },
    {
      "offset": 54.84,
      "duration": 0.78,
      "gain": 1
    }
  ],
  "spell:dark": [
    {
      "offset": 55.74,
      "duration": 0.72,
      "gain": 1
    },
    {
      "offset": 56.58,
      "duration": 0.72,
      "gain": 1
    }
  ],
  "motion:roll": [
    {
      "offset": 57.42,
      "duration": 0.37,
      "gain": 1
    },
    {
      "offset": 57.91,
      "duration": 0.37,
      "gain": 1
    }
  ],
  "motion:blink": [
    {
      "offset": 58.4,
      "duration": 0.45,
      "gain": 1
    },
    {
      "offset": 58.97,
      "duration": 0.45,
      "gain": 1
    }
  ],
  "motion:water": [
    {
      "offset": 59.54,
      "duration": 0.41,
      "gain": 1
    },
    {
      "offset": 60.07,
      "duration": 0.41,
      "gain": 1
    }
  ],
  "material:stone:impact": [
    {
      "offset": 60.6,
      "duration": 0.32,
      "gain": 1
    },
    {
      "offset": 61.04,
      "duration": 0.32,
      "gain": 1
    }
  ],
  "material:wood:impact": [
    {
      "offset": 61.48,
      "duration": 0.29,
      "gain": 1
    },
    {
      "offset": 61.89,
      "duration": 0.29,
      "gain": 1
    }
  ],
  "material:ice:impact": [
    {
      "offset": 62.3,
      "duration": 0.42,
      "gain": 1
    },
    {
      "offset": 62.84,
      "duration": 0.42,
      "gain": 1
    }
  ],
  "material:wet:impact": [
    {
      "offset": 63.38,
      "duration": 0.36,
      "gain": 1
    },
    {
      "offset": 63.86,
      "duration": 0.36,
      "gain": 1
    }
  ],
  "material:fire:impact": [
    {
      "offset": 64.34,
      "duration": 0.43,
      "gain": 1
    },
    {
      "offset": 64.89,
      "duration": 0.43,
      "gain": 1
    }
  ],
  "material:stone:hurt": [
    {
      "offset": 60.6,
      "duration": 0.32,
      "gain": 1
    },
    {
      "offset": 61.04,
      "duration": 0.32,
      "gain": 1
    }
  ],
  "material:wood:hurt": [
    {
      "offset": 61.48,
      "duration": 0.29,
      "gain": 1
    },
    {
      "offset": 61.89,
      "duration": 0.29,
      "gain": 1
    }
  ],
  "material:ice:hurt": [
    {
      "offset": 62.3,
      "duration": 0.42,
      "gain": 1
    },
    {
      "offset": 62.84,
      "duration": 0.42,
      "gain": 1
    }
  ],
  "material:wet:hurt": [
    {
      "offset": 63.38,
      "duration": 0.36,
      "gain": 1
    },
    {
      "offset": 63.86,
      "duration": 0.36,
      "gain": 1
    }
  ],
  "material:fire:hurt": [
    {
      "offset": 64.34,
      "duration": 0.43,
      "gain": 1
    },
    {
      "offset": 64.89,
      "duration": 0.43,
      "gain": 1
    }
  ]
};
