export const MAPS={forest:{name:'翡翠幽林',subtitle:'穿过古木与遗迹，追寻林心的回声',ground:0x284b3b,fog:0x173d39,leaf:0x287456,accent:0xecc988,slow:'泥地'},snow:{name:'霜月峡谷',subtitle:'冰晶照亮雪路，寒风掩藏猎手',ground:0x96b7bd,fog:0x769daa,leaf:0x456e7d,accent:0x9ae9ff,slow:'深雪'},ash:{name:'赤烬荒原',subtitle:'越过熔岩裂隙，唤醒沉睡的守卫',ground:0x5c4544,fog:0x382e3c,leaf:0x69545d,accent:0xffa25d,slow:'灰烬'}};
export const WEAPONS={rifle:{id:'rifle',name:'游侠连发枪',rate:3,damage:12,count:1,speed:27,range:24,color:0xffdc91},shotgun:{id:'shotgun',name:'碎岩霰弹枪',rate:1,damage:10,count:5,speed:25,range:13,color:0xffbe69},fire:{id:'fire',name:'烬火法杖',rate:.9,damage:30,count:1,speed:14,range:22,color:0xff743b},pistol:{id:'pistol',name:'银鸦手枪',rate:2.2,damage:19,count:1,speed:32,range:25,color:0xffecc2},shuriken:{id:'shuriken',name:'月刃飞镖',rate:1.4,damage:13,count:3,speed:22,range:19,color:0x95fff0},dark:{id:'dark',name:'夜幕法器',rate:1,damage:26,count:1,speed:12,range:23,color:0xc5a2ff}};
export function weaponFor(hero,index){return WEAPONS[(hero==='silver'?['pistol','shuriken','dark']:['rifle','shotgun','fire'])[index]];}
export function seeded(seed){let n=seed>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
export function experienceNeeded(level){return Math.floor(15+level*5+level*level*.5);}
export function grantExperience(p,n){p.xp+=n;while(p.xp>=experienceNeeded(p.level)){p.xp-=experienceNeeded(p.level);p.level++;p.pending++;p.maxHp+=4;p.hp=Math.min(p.maxHp,p.hp+4);}}
export const UPGRADES=[{id:'power',name:'磨砺锋芒',text:'武器伤害 +18%',icon:'✦',max:5},{id:'haste',name:'疾风节拍',text:'射速 +15%',icon:'»',max:4},{id:'fire',name:'陨火降临',text:'周期召唤陨火，轰击附近怪群',icon:'☄',max:3},{id:'ice',name:'霜华绽放',text:'周期释放冰晶环，伤害并减速',icon:'❄',max:3},{id:'storm',name:'雷霆回响',text:'周期落雷，连锁附近敌人',icon:'ϟ',max:3},{id:'vitality',name:'坚韧之心',text:'生命上限 +24，并恢复 24',icon:'♡',max:4},{id:'stride',name:'轻盈步伐',text:'移动速度 +8%，闪避冷却缩短',icon:'➶',max:3},{id:'magnet',name:'灵光牵引',text:'经验吸取范围增加',icon:'◎',max:3}];
export function chooseUpgrades(p,random=Math.random){const pool=UPGRADES.filter(u=>(p.upgrades[u.id]||0)<u.max);const result=[];while(pool.length&&result.length<3)result.push(pool.splice(Math.floor(random()*pool.length),1)[0]);return result;}
export const ENEMIES={mushroom:{hp:28,speed:2.7,damage:10,xp:6,size:.55},wolf:{hp:24,speed:4.4,damage:12,xp:8,size:.6},golem:{hp:130,speed:1.7,damage:22,xp:23,size:1},spitter:{hp:52,speed:2.3,damage:13,xp:12,size:.6},shaman:{hp:75,speed:2,damage:8,xp:18,size:.65}};
export function segmentDistance(px,pz,ax,az,bx,bz){const x=bx-ax,z=bz-az,l=x*x+z*z,t=l?Math.max(0,Math.min(1,((px-ax)*x+(pz-az)*z)/l)):0;return Math.hypot(px-ax-x*t,pz-az-z*t);}
