import test from 'node:test';import assert from 'node:assert/strict';import * as T from '../vendor/three.module.js';
import{makeBadger,animateBadger}from'../beast-model.js';import{badgerAttack}from'../badger-motion.js';
test('walking paws stay planted in world space and leave at least two supporting feet',()=>{for(const fps of[30,60,120]){const pet=makeBadger(),previous=[];let samples=0;for(let i=0;i<fps*3;i++){pet.position.z=1.15*i/fps;animateBadger(pet,i/fps,1.15,'roam');pet.updateMatrixWorld(true);assert(pet.userData.legs.filter(l=>l.planted).length>=2);for(const[j,l]of pet.userData.legs.entries()){const pos=l.paw.getWorldPosition(new T.Vector3());if(i>fps&&l.planted&&previous[j]?.planted){assert(pos.distanceTo(previous[j].pos)<.003,'planted paw skates');samples++;}previous[j]={pos,planted:l.planted};}}assert(samples>fps);}});
test('turning, stopping and interrupted attacks keep paws finite and return them to the ground',()=>{for(const fps of[30,60,120]){const pet=makeBadger();for(let i=0;i<fps*5;i++){const t=i/fps;let state=t<1?'roam':t<1.28?'wind':t<1.43?'pounce':t<2?'return':'look',speed=t<1?1.15:t<2?3:0;pet.rotation.y=Math.min(t,2)*.7;if(t<2){pet.position.x+=Math.sin(pet.rotation.y)*speed/fps;pet.position.z+=Math.cos(pet.rotation.y)*speed/fps;}animateBadger(pet,t,speed,state,state==='wind'?(t-1)/.28:state==='pounce'?(t-1.28)/.3:0,.7);pet.updateMatrixWorld(true);pet.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite)));}for(const leg of pet.userData.legs){const foot=leg.paw.getWorldPosition(new T.Vector3());assert(Math.abs(foot.y-.06)<.01);assert(leg.planted);}assert(Math.abs(pet.userData.jaw.rotation.x)<.001);}});
test('low pounce extends forelegs and closes the jaw at contact instead of bouncing like a ball',()=>{assert(badgerAttack('wind',1).crouch>.05);assert(badgerAttack('pounce',.25).jaw>.25);assert(badgerAttack('pounce',.68).jaw<.01);for(let i=0;i<=100;i++){const p=badgerAttack('pounce',i/100);assert(p.air<=.17&&p.air>=0);}assert(badgerAttack('recover',1).crouch<1e-9);});


test('walk uses longer strides and catch-up does not degenerate into tiny rapid steps',()=>{for(const fps of[30,60,120])for(const speed of[1.15,3,6,10]){const pet=makeBadger(),counts=[0,0,0,0],last=[],landings=[];for(let i=0;i<fps*10;i++){pet.position.z=speed*i/fps;animateBadger(pet,i/fps,speed,'return');pet.userData.legs.forEach((l,j)=>{if(l.lastLift!==undefined&&l.lastLift!==last[j]){counts[j]++;last[j]=l.lastLift;if(j===0&&i>fps)landings.push(l.to.z);}});}for(const n of counts)assert(n/10<=(speed===1.15?1.9:3.9),`rapid steps at ${fps} FPS / ${speed}m/s`);if(speed===1.15){assert(counts.every(n=>n>=13));assert(landings.slice(1).every((z,i)=>z-landings[i]>.55),'walking stride too short');}}});

test('standing has quiet holds, occasional glances and blinks without shuffling the planted feet',()=>{for(const fps of[30,60,120]){const pet=makeBadger(),previous=[];let quiet=0,samples=0,minYaw=1,maxYaw=-1,minEye=1,oldYaw=0;for(let i=0;i<fps*10;i++){animateBadger(pet,i/fps,0,'look');pet.updateMatrixWorld(true);const d=pet.userData,yaw=d.head.rotation.y;minYaw=Math.min(minYaw,yaw);maxYaw=Math.max(maxYaw,yaw);minEye=Math.min(minEye,d.eyes[0].scale.y);if(i>fps){samples++;if(Math.abs(yaw-oldYaw)*fps<.01)quiet++;for(const[j,l]of d.legs.entries()){const p=l.paw.getWorldPosition(new T.Vector3());assert(l.planted,'idle keeps lifting paws');if(previous[j])assert(p.distanceTo(previous[j])<.002,'idle foot skates');previous[j]=p;}}oldYaw=yaw;}assert(quiet/samples>.35,'idle head never pauses');assert(minYaw<-.10&&maxYaw>.20);assert(minEye<.3);}});


test('downed pose settles and revival restores feet and rig without preserving the fallen rotation',()=>{const pet=makeBadger();for(let i=0;i<120;i++)animateBadger(pet,i/60,0,'down');assert(pet.userData.rig.rotation.z>1.1);for(let i=120;i<240;i++)animateBadger(pet,i/60,0,'look');pet.updateMatrixWorld(true);assert(Math.abs(pet.userData.rig.rotation.z)<.02);for(const l of pet.userData.legs)assert(Math.abs(l.paw.getWorldPosition(new T.Vector3()).y-.06)<.01);pet.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite)));});
