import{LINGYA_HOP_DURATION,LINGYA_HOP_DISTANCE,lingyaHopScale,lingyaHopPose}from'../lingya-motion.js';
import test from 'node:test';import assert from 'node:assert/strict';
import{BeastCompanion,sideHopTravel}from'../beast-companion.js';import{weaponStats,takeUpgrade,chooseUpgrades}from'../rules.js';import{makeBadger,animateBadger,boneBoomerang}from'../beast-model.js';
function setup(path){const p={x:0,z:0,heroId:'lingya',weaponId:'boomerang',level:8,upgrades:{}},enemies=[{x:0,z:3,size:.5,hp:1000,alive:true},{x:3,z:0,size:.5,hp:1000,alive:true}],hits=[],effects=[];if(path)for(let i=0;i<3;i++)takeUpgrade(p,'path:'+path);let active=true,blocked=false;
 const api={player:()=>p,stats:()=>weaponStats(p),active:()=>active,foes:()=>enemies,visible:()=>true,clear:()=>!blocked,move:(o,x,z)=>{if(!blocked){o.x+=x;o.z+=z}},home:()=>({x:-1,z:0}),damage:(e,n)=>{e.hp-=n;hits.push({e,n})},fx:(...a)=>effects.push(a)},pet=new BeastCompanion(api);return{p,enemies,hits,effects,pet,active:v=>active=v,blocked:v=>blocked=v,step:t=>{for(let i=0;i<Math.ceil(t*60);i++)pet.update(1/60)}};
}
test('partner obeys aimed target, strikes only once, rests, and has independent health',()=>{const f=setup();f.pet.order(0);assert.equal(f.pet.command,f.enemies[0]);f.step(2);assert.equal(f.hits.length,1);assert.equal(f.hits[0].e,f.enemies[0]);assert(f.enemies[0].stagger<=.22);assert(f.pet.cool>0);assert.equal(f.pet.hp,f.pet.maxHp);f.enemies.forEach(e=>e.alive=false);f.step(3);assert.equal(f.hits.length,1);assert(Math.hypot(f.pet.x-f.p.x,f.pet.z-f.p.z)<4.5);});
test('recall cancels a pending pounce and pause freezes companion, command, traps',()=>{const f=setup('boomerang_snare');f.pet.order(0);f.step(.9);f.pet.recall();f.step(1);assert.equal(f.hits.length,0);for(let i=0;i<6;i++)f.pet.order(0);assert(f.pet.traps.length);const before=JSON.stringify(f.pet.traps),now=f.pet.now;f.active(false);f.step(3);assert.equal(f.pet.now,now);assert.equal(JSON.stringify(f.pet.traps),before);});
test('walls prevent command damage; dead targets cannot produce a ghost hit',()=>{const f=setup();f.blocked(true);f.pet.order(0);f.step(3);assert.equal(f.hits.length,0);f.blocked(false);f.pet.order(0);f.step(.1);f.enemies[0].alive=false;f.enemies[1].alive=false;f.step(3);assert.equal(f.hits.length,0);});
test('pincer rewards a marked target while trap route arms, caps and expires without boss stun',()=>{const f=setup('boomerang_pincer');f.pet.order(0);f.pet.marked(f.enemies[0]);f.step(2);assert(f.hits[0].n>weaponStats(f.p).petDamage);assert.equal(f.pet.traps.length,0);
 const t=setup('boomerang_snare');for(let i=0;i<15;i++)t.pet.order(Math.PI);assert.equal(t.pet.traps.length,3);t.enemies[0].z=.4;t.enemies[0].boss=true;t.step(.3);assert.equal(t.hits.length,0);t.step(.3);assert(t.enemies[0].slow>0);assert(!t.enemies[0].stagger);assert.equal(t.pet.traps.length,0);for(let i=0;i<3;i++)t.pet.order(Math.PI);t.enemies[0].z=20;t.step(9);assert.equal(t.pet.traps.length,0);
 assert(!chooseUpgrades(f.p).some(u=>['fire','ice','storm','veil'].includes(u.id)));assert(!takeUpgrade(f.p,'path:boomerang_snare'));
});
test('side hop is frame independent; articulated badger poses remain finite and pooled',()=>{for(const fps of[30,60,120]){let t=LINGYA_HOP_DURATION,total=0;while(t>0){const next=Math.max(0,t-1/fps);total+=sideHopTravel(next)-sideHopTravel(t);t=next;}assert(Math.abs(total-LINGYA_HOP_DISTANCE)<1e-8);const a=makeBadger(),b=makeBadger();assert.equal(a.userData.body.geometry,b.userData.body.geometry);for(let i=0;i<fps*4;i++){animateBadger(a,i/fps,4,i<fps?'follow':i<fps*2?'wind':'pounce',(i%fps)/fps);a.updateMatrixWorld(true);a.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite)));}assert.notEqual(a.userData.legs[0].joint.rotation.x,b.userData.legs[0].joint.rotation.x);}assert.equal(boneBoomerang().children[0].geometry,boneBoomerang().children[0].geometry);});

test('pet explores world-space goals, pauses to sniff, and does not orbit mouse aim',()=>{const f=setup();f.enemies.length=0;const states=new Set(),points=[];for(let i=0;i<900;i++){f.p.aimAngle=i*.2;f.pet.update(1/60);states.add(f.pet.state);points.push([f.pet.x,f.pet.z]);assert(Math.hypot(f.pet.x,f.pet.z)<4.2);}assert(states.has('roam')&&states.has('sniff')&&states.has('look'));assert(Math.max(...points.map(p=>Math.hypot(...p)))>2);f.pet.state='sniff';f.pet.decisionAt=f.pet.now+2;f.pet.vx=f.pet.vz=0;const start=[f.pet.x,f.pet.z];f.step(1);assert.deepEqual([f.pet.x,f.pet.z],start);});
test('leash has separate catch-up and stop distances, recall interrupts every attack phase',()=>{const f=setup();f.enemies.length=0;f.p.x=22;f.pet.update(1/60);assert.equal(f.pet.state,'return');f.step(3);assert.notEqual(f.pet.state,'return');assert(Math.hypot(f.pet.x-f.p.x,f.pet.z-f.p.z)<5);for(const state of ['approach','wind','pounce','recover']){f.pet.state=state;f.pet.target={alive:true};f.pet.recall();assert.equal(f.pet.state,'return');assert.equal(f.pet.target,null);assert(f.pet.cool>=1.1);}});
test('nearby autonomous attacks rest, cannot chase distant targets, and explicit aim wins',()=>{const f=setup();f.enemies[0].z=2.5;f.step(2);assert.equal(f.hits.length,1);const n=f.hits.length;f.step(1);assert.equal(f.hits.length,n);f.step(3);assert(f.hits.length>n);const far=setup();far.enemies.forEach(e=>{e.x=20;e.z=20;});far.step(8);assert.equal(far.hits.length,0);const hidden=setup();hidden.pet.api.visible=()=>false;hidden.step(5);assert(hidden.hits.length>0);const aimed=setup();aimed.pet.order(Math.PI/2);aimed.step(2);assert.equal(aimed.hits[0].e,aimed.enemies[1]);});
test('hop has a grounded push, asymmetric airborne tuck and a smooth landing envelope',()=>{const pose=t=>lingyaHopPose(LINGYA_HOP_DURATION*(1-t));assert.equal(pose(0).height,0);assert(pose(.1).push>0);assert(pose(.45).height>.15&&pose(.45).height<.17);assert(pose(.85).land>0);assert.equal(pose(1).height,0);assert.equal(pose(1).weight,0);for(let i=0;i<=100;i++)assert(Object.values(pose(i/100)).every(Number.isFinite));});

test('aim commands do not count as thrown bones or create traps before release',()=>{const f=setup('boomerang_snare');for(let i=0;i<6;i++)f.pet.order(0,false);assert.equal(f.pet.command,f.enemies[0]);assert.equal(f.pet.throwCount,0);assert.equal(f.pet.traps.length,0);for(let i=0;i<3;i++)f.pet.order(0);assert.equal(f.pet.traps.length,1);});

test('longer hop travels promptly, stays monotone, and keeps water slower than dry ground',()=>{assert.equal(LINGYA_HOP_DISTANCE,6.2);assert(sideHopTravel(LINGYA_HOP_DURATION*.75)>1);let last=0;for(let i=0;i<=100;i++){const x=sideHopTravel(LINGYA_HOP_DURATION*(1-i/100));assert(x>=last-1e-9);last=x;}assert.equal(lingyaHopScale(.5,0),.9);assert.equal(lingyaHopScale(.5,.8),.5);});

test('pounce commits once, waits for bite contact and stops in front of the enemy',()=>{const f=setup();f.pet.x=0;f.pet.z=0;f.pet.state='pounce';f.pet.elapsed=0;f.pet.attackAngle=0;f.pet.target=f.enemies[0];f.enemies[0].z=2;f.step(.12);assert.equal(f.hits.length,0);f.step(.08);assert.equal(f.hits.length,1);const z=f.pet.z;f.step(.10);assert(Math.abs(f.pet.z-z)<.001);assert(f.pet.z<f.enemies[0].z-.9);});


test('owner movement and camera scrolling do not cancel a committed attack',()=>{for(const fps of[30,60,120]){const f=setup();f.pet.order(0);for(let i=0;i<fps*2;i++){f.p.x+=5/fps;if(i>fps/2)f.pet.api.visible=()=>false;f.pet.update(1/fps);}assert(f.hits.length>0,`moving owner ${fps}`);assert(!f.pet.forcedReturn);}});
test('ordinary following can acquire a nearby enemy without touching the owner first',()=>{const f=setup();f.p.x=12;f.pet.state='return';f.pet.cool=0;f.pet.order(Math.PI,false);assert.equal(f.pet.command,null);f.step(2);assert(f.hits.length>0);assert(!f.pet.forcedReturn);});
test('hard leash cancels combat only far away and permits reengagement inside the inner leash',()=>{const f=setup();f.pet.target=f.enemies[0];f.pet.state='wind';f.p.x=22;f.pet.update(1/60);assert(f.pet.forcedReturn);assert.equal(f.pet.target,null);assert.equal(f.pet.state,'return');f.enemies[0].x=12;f.enemies[0].z=0;f.enemies[1].alive=false;for(let i=0;i<180;i++)f.pet.update(1/60);assert(!f.pet.forcedReturn);assert(f.hits.length>0);assert(Math.hypot(f.pet.x-f.p.x,f.pet.z-f.p.z)>4);});
test('an empty aim command cannot suppress independent combat',()=>{const f=setup();for(let i=0;i<180;i++){f.pet.order(Math.PI,false);f.pet.update(1/60);}assert(f.hits.length>0);});


test('pet can intercept a moving enemy while its owner keeps running',()=>{for(const fps of[30,60,120]){const f=setup();f.enemies[1].alive=false;f.pet.order(0);for(let i=0;i<fps*2.5;i++){f.p.x+=4/fps;f.enemies[0].x+=2.5/fps;f.pet.update(1/fps);}assert(f.hits.length>0,`moving prey ${fps}`);}});


test('pet health scales with the owner without healing existing damage on every update',()=>{const f=setup();assert.equal(f.pet.maxHp,206);assert(f.pet.takeDamage(30));assert.equal(f.pet.hp,176);assert(!f.pet.takeDamage(30));f.step(1);assert.equal(f.pet.hp,176);f.p.level++;f.p.upgrades.vitality=1;f.step(.02);assert.equal(f.pet.maxHp,234);assert.equal(f.pet.hp,204);for(const n of[-2,0,NaN,Infinity])assert(!f.pet.takeDamage(n));});
test('death cancels combat, stops movement and revives once at a safe home after the full countdown',()=>{const f=setup();f.pet.order(0);f.pet.state='pounce';f.pet.target=f.enemies[0];f.pet.takeDamage(1000);const point=[f.pet.x,f.pet.z];assert(!f.pet.alive);assert.equal(f.pet.hp,0);assert.equal(f.pet.state,'down');f.pet.recall();f.step(11);assert.deepEqual([f.pet.x,f.pet.z],point);assert.equal(f.hits.length,0);assert(!f.pet.alive);f.step(1.1);assert(f.pet.alive);assert.equal(f.pet.hp,f.pet.maxHp);assert.equal(f.effects.filter(e=>e[0]==='petRevive').length,1);assert(Math.hypot(f.pet.x+1,f.pet.z)<.1);assert(!f.pet.takeDamage(1000));f.step(2);assert(f.pet.takeDamage(5));});
test('pause freezes revival, blocked revival retries and level growth cannot revive a downed pet',()=>{const f=setup();f.pet.takeDamage(1000);f.active(false);f.step(30);assert.equal(f.pet.reviveLeft,12);f.active(true);f.pet.api.home=()=>null;f.p.level=12;f.step(20);assert.equal(f.pet.hp,0);assert(!f.pet.alive);assert.equal(f.pet.reviveLeft,0);assert.equal(f.pet.maxHp,238);f.pet.api.home=()=>({x:3,z:1});f.step(.6);assert(f.pet.alive);assert.equal(f.pet.hp,238);});
test('owner traps remain usable while the pet is down, but no bite or target command can fire',()=>{const f=setup('boomerang_snare');f.pet.takeDamage(1000);for(let i=0;i<3;i++)f.pet.order(0);assert.equal(f.pet.command,null);assert.equal(f.pet.traps.length,1);f.step(2);assert.equal(f.hits.length,0);assert(!f.pet.alive);});

test('explicit cooperative cover runs to the old owner position and resumes combat without teleporting',()=>{const f=setup();f.enemies.length=0;f.pet.x=5;f.pet.z=0;f.pet.cover(0,0);assert.equal(f.pet.state,'cover');assert(f.pet.inv>0);f.pet.update(1/60);assert(f.pet.x>4.9);f.p.x=5;f.step(1.65);assert(Math.hypot(f.pet.x,f.pet.z)<.7);assert.notEqual(f.pet.state,'cover');const dead=setup();dead.pet.takeDamage(999);dead.pet.cover(4,4);assert.equal(dead.pet.state,'down');});

test('rest restores companion health only near the owner, outside combat, after damage cooldown',()=>{
 const f=setup();f.enemies.length=0;f.pet.cool=999;f.pet.takeDamage(80);const hp=f.pet.hp;
 f.step(3.8);assert.equal(f.pet.hp,hp);f.step(1.2);assert(f.pet.hp>hp+6&&f.pet.hp<hp+10);
 f.active(false);const held=f.pet.hp;f.step(3);assert.equal(f.pet.hp,held);f.active(true);
 f.enemies.push({x:f.pet.x,z:f.pet.z+1,alive:true});f.step(1);assert.equal(f.pet.hp,held);
 f.enemies.length=0;f.pet.takeDamage(5);const hurt=f.pet.hp;f.step(3);assert.equal(f.pet.hp,hurt);
 f.pet.api.move=()=>{};f.pet.x=f.p.x+8;f.step(3);assert.equal(f.pet.hp,hurt);
 f.pet.x=f.p.x;f.pet.z=f.p.z;f.step(30);assert.equal(f.pet.hp,f.pet.maxHp);
});
