import test from 'node:test';import assert from 'node:assert/strict';
import{BeastCompanion,sideHopTravel}from'../beast-companion.js';import{weaponStats,takeUpgrade,chooseUpgrades}from'../rules.js';import{makeBadger,animateBadger,boneBoomerang}from'../beast-model.js';
function setup(path){const p={x:0,z:0,heroId:'lingya',weaponId:'boomerang',level:8,upgrades:{}},enemies=[{x:0,z:3,size:.5,hp:1000,alive:true},{x:3,z:0,size:.5,hp:1000,alive:true}],hits=[],effects=[];if(path)for(let i=0;i<3;i++)takeUpgrade(p,'path:'+path);let active=true,blocked=false;
 const api={player:()=>p,stats:()=>weaponStats(p),active:()=>active,foes:()=>enemies,visible:()=>true,clear:()=>!blocked,move:(o,x,z)=>{if(!blocked){o.x+=x;o.z+=z}},home:()=>({x:-1,z:0}),damage:(e,n)=>{e.hp-=n;hits.push({e,n})},fx:(...a)=>effects.push(a)},pet=new BeastCompanion(api);return{p,enemies,hits,effects,pet,active:v=>active=v,blocked:v=>blocked=v,step:t=>{for(let i=0;i<Math.ceil(t*60);i++)pet.update(1/60)}};
}
test('partner obeys aimed target, strikes only once, rests, and does not tank',()=>{const f=setup();f.pet.order(0);assert.equal(f.pet.command,f.enemies[0]);f.step(2);assert.equal(f.hits.length,1);assert.equal(f.hits[0].e,f.enemies[0]);assert(f.enemies[0].stagger<=.22);assert(f.pet.cool>0);assert(!('hp'in f.pet));f.step(3);assert.equal(f.hits.length,1);assert(Math.hypot(f.pet.x-f.p.x,f.pet.z-f.p.z)<2);});
test('recall cancels a pending pounce and pause freezes companion, command, traps',()=>{const f=setup('boomerang_snare');f.pet.order(0);f.step(.9);f.pet.recall();f.step(1);assert.equal(f.hits.length,0);for(let i=0;i<6;i++)f.pet.order(0);assert(f.pet.traps.length);const before=JSON.stringify(f.pet.traps),now=f.pet.now;f.active(false);f.step(3);assert.equal(f.pet.now,now);assert.equal(JSON.stringify(f.pet.traps),before);});
test('walls prevent command damage; dead targets cannot produce a ghost hit',()=>{const f=setup();f.blocked(true);f.pet.order(0);f.step(3);assert.equal(f.hits.length,0);f.blocked(false);f.pet.order(0);f.step(.1);f.enemies[0].alive=false;f.step(3);assert.equal(f.hits.length,0);});
test('pincer rewards a marked target while trap route arms, caps and expires without boss stun',()=>{const f=setup('boomerang_pincer');f.pet.order(0);f.pet.marked(f.enemies[0]);f.step(2);assert(f.hits[0].n>weaponStats(f.p).petDamage);assert.equal(f.pet.traps.length,0);
 const t=setup('boomerang_snare');for(let i=0;i<15;i++)t.pet.order(Math.PI);assert.equal(t.pet.traps.length,3);t.enemies[0].z=.4;t.enemies[0].boss=true;t.step(.3);assert.equal(t.hits.length,0);t.step(.3);assert(t.enemies[0].slow>0);assert(!t.enemies[0].stagger);assert.equal(t.pet.traps.length,0);for(let i=0;i<3;i++)t.pet.order(Math.PI);t.enemies[0].z=20;t.step(9);assert.equal(t.pet.traps.length,0);
 assert(!chooseUpgrades(f.p).some(u=>['fire','ice','storm','veil'].includes(u.id)));assert(!takeUpgrade(f.p,'path:boomerang_snare'));
});
test('side hop is frame independent; articulated badger poses remain finite and pooled',()=>{for(const fps of[30,60,120]){let t=.3,total=0;while(t>0){const next=Math.max(0,t-1/fps);total+=sideHopTravel(next)-sideHopTravel(t);t=next;}assert(Math.abs(total-3.8)<1e-8);const a=makeBadger(),b=makeBadger();assert.equal(a.userData.body.geometry,b.userData.body.geometry);for(let i=0;i<fps*4;i++){animateBadger(a,i/fps,4,i<fps?'follow':i<fps*2?'wind':'pounce',(i%fps)/fps);a.updateMatrixWorld(true);a.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite)));}assert.notEqual(a.userData.legs[0].joint.rotation.x,b.userData.legs[0].joint.rotation.x);}assert.equal(boneBoomerang().children[0].geometry,boneBoomerang().children[0].geometry);});
