import{LINGYA_HOP_DURATION,LINGYA_HOP_DISTANCE,lingyaHopScale,lingyaHopPose}from'../lingya-motion.js';
import test from 'node:test';import assert from 'node:assert/strict';
import{BeastCompanion,sideHopTravel}from'../beast-companion.js';import{weaponStats,takeUpgrade,chooseUpgrades}from'../rules.js';import{makeBadger,animateBadger,boneBoomerang}from'../beast-model.js';
function setup(path){const p={x:0,z:0,heroId:'lingya',weaponId:'boomerang',level:8,upgrades:{}},enemies=[{x:0,z:3,size:.5,hp:1000,alive:true},{x:3,z:0,size:.5,hp:1000,alive:true}],hits=[],effects=[];if(path)for(let i=0;i<3;i++)takeUpgrade(p,'path:'+path);let active=true,blocked=false;
 const api={player:()=>p,stats:()=>weaponStats(p),active:()=>active,foes:()=>enemies,visible:()=>true,clear:()=>!blocked,move:(o,x,z)=>{if(!blocked){o.x+=x;o.z+=z}},home:()=>({x:-1,z:0}),damage:(e,n)=>{e.hp-=n;hits.push({e,n})},fx:(...a)=>effects.push(a)},pet=new BeastCompanion(api);return{p,enemies,hits,effects,pet,active:v=>active=v,blocked:v=>blocked=v,step:t=>{for(let i=0;i<Math.ceil(t*60);i++)pet.update(1/60)}};
}
test('partner obeys aimed target, strikes only once, rests, and does not tank',()=>{const f=setup();f.pet.order(0);assert.equal(f.pet.command,f.enemies[0]);f.step(2);assert.equal(f.hits.length,1);assert.equal(f.hits[0].e,f.enemies[0]);assert(f.enemies[0].stagger<=.22);assert(f.pet.cool>0);assert(!('hp'in f.pet));f.enemies.forEach(e=>e.alive=false);f.step(3);assert.equal(f.hits.length,1);assert(Math.hypot(f.pet.x-f.p.x,f.pet.z-f.p.z)<4.5);});
test('recall cancels a pending pounce and pause freezes companion, command, traps',()=>{const f=setup('boomerang_snare');f.pet.order(0);f.step(.9);f.pet.recall();f.step(1);assert.equal(f.hits.length,0);for(let i=0;i<6;i++)f.pet.order(0);assert(f.pet.traps.length);const before=JSON.stringify(f.pet.traps),now=f.pet.now;f.active(false);f.step(3);assert.equal(f.pet.now,now);assert.equal(JSON.stringify(f.pet.traps),before);});
test('walls prevent command damage; dead targets cannot produce a ghost hit',()=>{const f=setup();f.blocked(true);f.pet.order(0);f.step(3);assert.equal(f.hits.length,0);f.blocked(false);f.pet.order(0);f.step(.1);f.enemies[0].alive=false;f.step(3);assert.equal(f.hits.length,0);});
test('pincer rewards a marked target while trap route arms, caps and expires without boss stun',()=>{const f=setup('boomerang_pincer');f.pet.order(0);f.pet.marked(f.enemies[0]);f.step(2);assert(f.hits[0].n>weaponStats(f.p).petDamage);assert.equal(f.pet.traps.length,0);
 const t=setup('boomerang_snare');for(let i=0;i<15;i++)t.pet.order(Math.PI);assert.equal(t.pet.traps.length,3);t.enemies[0].z=.4;t.enemies[0].boss=true;t.step(.3);assert.equal(t.hits.length,0);t.step(.3);assert(t.enemies[0].slow>0);assert(!t.enemies[0].stagger);assert.equal(t.pet.traps.length,0);for(let i=0;i<3;i++)t.pet.order(Math.PI);t.enemies[0].z=20;t.step(9);assert.equal(t.pet.traps.length,0);
 assert(!chooseUpgrades(f.p).some(u=>['fire','ice','storm','veil'].includes(u.id)));assert(!takeUpgrade(f.p,'path:boomerang_snare'));
});
test('side hop is frame independent; articulated badger poses remain finite and pooled',()=>{for(const fps of[30,60,120]){let t=LINGYA_HOP_DURATION,total=0;while(t>0){const next=Math.max(0,t-1/fps);total+=sideHopTravel(next)-sideHopTravel(t);t=next;}assert(Math.abs(total-LINGYA_HOP_DISTANCE)<1e-8);const a=makeBadger(),b=makeBadger();assert.equal(a.userData.body.geometry,b.userData.body.geometry);for(let i=0;i<fps*4;i++){animateBadger(a,i/fps,4,i<fps?'follow':i<fps*2?'wind':'pounce',(i%fps)/fps);a.updateMatrixWorld(true);a.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite)));}assert.notEqual(a.userData.legs[0].joint.rotation.x,b.userData.legs[0].joint.rotation.x);}assert.equal(boneBoomerang().children[0].geometry,boneBoomerang().children[0].geometry);});

test('pet explores world-space goals, pauses to sniff, and does not orbit mouse aim',()=>{const f=setup();f.enemies.length=0;const states=new Set(),points=[];for(let i=0;i<900;i++){f.p.aimAngle=i*.2;f.pet.update(1/60);states.add(f.pet.state);points.push([f.pet.x,f.pet.z]);assert(Math.hypot(f.pet.x,f.pet.z)<4.2);}assert(states.has('roam')&&states.has('sniff')&&states.has('look'));assert(Math.max(...points.map(p=>Math.hypot(...p)))>2);f.pet.state='sniff';f.pet.decisionAt=f.pet.now+2;f.pet.vx=f.pet.vz=0;const start=[f.pet.x,f.pet.z];f.step(1);assert.deepEqual([f.pet.x,f.pet.z],start);});
test('leash has separate catch-up and stop distances, recall interrupts every attack phase',()=>{const f=setup();f.enemies.length=0;f.p.x=8;f.pet.update(1/60);assert.equal(f.pet.state,'return');f.step(3);assert.notEqual(f.pet.state,'return');assert(Math.hypot(f.pet.x-f.p.x,f.pet.z-f.p.z)<3.5);for(const state of ['approach','wind','pounce','recover']){f.pet.state=state;f.pet.target={alive:true};f.pet.recall();assert.equal(f.pet.state,'return');assert.equal(f.pet.target,null);assert(f.pet.cool>=1.1);}});
test('nearby autonomous attacks rest, cannot chase distant/offscreen targets, and explicit aim wins',()=>{const f=setup();f.step(2);assert.equal(f.hits.length,1);const n=f.hits.length;f.step(1);assert.equal(f.hits.length,n);f.step(3);assert(f.hits.length>n);const far=setup();far.enemies.forEach(e=>{e.x=20;e.z=20;});far.step(8);assert.equal(far.hits.length,0);const hidden=setup();hidden.pet.api.visible=()=>false;hidden.step(5);assert.equal(hidden.hits.length,0);const aimed=setup();aimed.pet.order(Math.PI/2);aimed.step(2);assert.equal(aimed.hits[0].e,aimed.enemies[1]);});
test('hop has a grounded push, asymmetric airborne tuck and a smooth landing envelope',()=>{const pose=t=>lingyaHopPose(LINGYA_HOP_DURATION*(1-t));assert.equal(pose(0).height,0);assert(pose(.1).height<0);assert(pose(.38).height>.29);assert(pose(.9).height<0);assert.equal(pose(1).height,0);assert.equal(pose(1).tuck,0);for(let i=0;i<=100;i++)assert(Object.values(pose(i/100)).every(Number.isFinite));});

test('aim commands do not count as thrown bones or create traps before release',()=>{const f=setup('boomerang_snare');for(let i=0;i<6;i++)f.pet.order(0,false);assert.equal(f.pet.command,f.enemies[0]);assert.equal(f.pet.throwCount,0);assert.equal(f.pet.traps.length,0);for(let i=0;i<3;i++)f.pet.order(0);assert.equal(f.pet.traps.length,1);});

test('longer hop travels promptly, stays monotone, and keeps water slower than dry ground',()=>{assert.equal(LINGYA_HOP_DISTANCE,6.2);assert(sideHopTravel(LINGYA_HOP_DURATION*.75)>1);let last=0;for(let i=0;i<=100;i++){const x=sideHopTravel(LINGYA_HOP_DURATION*(1-i/100));assert(x>=last-1e-9);last=x;}assert.equal(lingyaHopScale(.5,0),.9);assert.equal(lingyaHopScale(.5,.8),.5);});
