const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
for(const [width,height,touch]of[[1440,900,false],[844,390,true],[390,844,true]]){
const p=await b.newPage({viewport:{width,height},hasTouch:touch}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{const raf=requestAnimationFrame;window.requestAnimationFrame=cb=>{window.nextFrame=cb;return raf(t=>{if(!window.freezeGame)cb(t)})};});await p.goto(process.env.TEST_URL||'http://127.0.0.1:8899/');await p.waitForFunction(()=>window.game3d&&!document.querySelector('#start').disabled,null,{polling:100,timeout:60000});await p.locator('[data-hero=tide]').click();await p.locator('#travel-tab').click();await p.locator('[data-map=coast]').click();await p.locator('#start').click();await p.evaluate(()=>freezeGame=true);await p.waitForTimeout(60);
const report=await p.evaluate(async()=>{const g=game3d,{terrainAt}=await import('./water.js?v=83'),check=(v,m)=>{if(!v)throw Error(m)},advance=t=>{for(let i=0;i<Math.ceil(t*60);i++){g.step(1/60);g.vfx.update(1/60)}},clear=()=>{for(const e of g.enemies){e.alive=false;e.mesh.removeFromParent()}},setup=()=>{g.select('tide','coast',0);g.start();g.world.obstacles=[];g.world.patches=[];g.world.ponds=[];g.world.sites=[];g.camera.position.x-=g.player.x;g.camera.position.z-=g.player.z;g.camera.lookAt(0,.5,0);g.camera.updateMatrixWorld(true);g.player.x=g.player.z=0;g.player.hp=g.player.maxHp=10000;g.player.attack=999;g.hero.rotation.y=0;g.controls.angle=0;g.controls.hasAim=true;g.controls.held=false},enemy=(x,z)=>{const e=g.spawn('reefturtle',x,z);e.speed=0;e.cool=999;e.hp=e.maxHp=1000;return e};
const {createSkinnedHero,disposeHero}=await import('./skinned-hero.js?v=83'),{animateActor}=await import('./world.js?v=83');for(const fps of[30,60,120]){const model=createSkinnedHero('tide','harpoon'),d=model.userData;check(d.skinned&&d.gun,'missing tide skeleton');for(let i=0;i<fps*6;i++){d.reloadDuration=.48;d.reloadPhase=(i/fps%.65)/.48;d.shotSerial=Math.floor(i/fps/.65);d.aimActive=true;d.waterDepth=i>fps*2&&i<fps*4?1:0;d.travelAngle=Math.sin(i/fps);d.dashTime=i<fps?Math.max(0,.3-i/fps):0;animateActor(model,i/fps,3,.1,0);model.updateMatrixWorld(true);model.traverse(o=>check(o.matrixWorld.elements.every(Number.isFinite),'invalid tide pose'));}d.aimActive=false;d.reloadPhase=1;d.waterDepth=0;d.dashTime=0;for(let i=0;i<fps;i++)animateActor(model,6+i/fps,0,0,0);check(d.waterBlend<.01&&Math.abs(d.rig.position.y)<.02,'tide water offsets accumulated');check(d.gun.parent===d.support.rightHand,'harpoon detached');disposeHero(model);}
setup();const front=enemy(0,3),side=enemy(2,2),back=enemy(0,-2);g.controls.held=true;g.player.attack=0;advance(.08);check(front.hp===1000,'damage before thrust');advance(.3);check(front.hp<1000&&side.hp===1000&&back.hp===1000,'narrow thrust failed');check(!g.bullets.length,'harpoon emitted bullets');g.controls.held=false;advance(.3);const z=front.z;g.player.harpoonCount=2;g.player.attack=0;g.controls.held=true;advance(.25);check(front.z<z-.5&&front.slow>0,'third thrust did not pull/slow');g.controls.held=false;
setup();const cancelled=enemy(0,3);g.controls.held=true;g.player.attack=0;advance(.04);g.controls.held=false;g.dash();advance(.35);check(cancelled.hp===1000,'dash failed to cancel strike');
setup();const blocked=enemy(0,3);g.world.obstacles.push({x:0,z:1.5,r:.4});g.controls.held=true;g.player.attack=0;advance(.4);check(blocked.hp===1000,'thrust through wall');g.controls.held=false;
g.select('tide','coast',0);g.start();g.player.inv=999;g.player.attack=999;const pond=g.world.ponds[0],rx=pond.rx;advance(20);check(pond.rx>rx*1.18,'tide did not expand');const bridge=g.world.bridges[0];check(terrainAt(g.world,bridge.x,bridge.z).speed===1,'bridge slowed player');const t=g.time;g.pause();g.step(10);check(g.time===t&&g.world.tide.high,'pause changed tide');g.resume();
g.select('tide','coast',0);g.start();g.player.hp=g.player.maxHp=10000;g.player.inv=999;g.player.attack=999;const s=g.world.sites[0];s.availableAt=0;g.player.x=s.x;g.player.z=s.z;advance(2.5);check(s.guards?.length>0,'lighthouse missing guards');for(let i=0;i<600&&g.state==='playing';i++){clear();g.step(1/60)}check(s.claimed&&g.state==='upgrade','lighthouse reward missing');check(s.eventRun.wave===1,'duplicate lighthouse guards');
setup();g.spawnBoss();const boss=g.boss;boss.x=0;boss.z=6;boss.mesh.position.set(0,0,6);const moves=new Set();for(let i=0;i<1800;i++){g.player.inv=999;clear();g.step(1/60);g.vfx.update(1/60);if(boss.move)moves.add(boss.move)}check(moves.size===3,'boss move missing');check(boss.mesh.userData.coastBoss,'boss model missing');boss.stage='walk';boss.cool=0;boss.turn=0;g.player.inv=0;g.step(.01);const zone=g.zones.find(z=>z.delay>0);check(zone,'boss telegraph missing');g.player.x=zone.x;g.player.z=zone.z;const hp=g.player.hp;advance(zone.delay+.1);check(g.player.hp<hp&&g.player.hexSlow>0,'boss wave did not damage/slow');return{moves:[...moves],hp:g.player.hp};});
await p.evaluate(()=>game3d.menu());await p.locator('#battle-guide').click();await p.locator('[data-guide-map=coast]').click();await p.waitForFunction(()=>[...document.querySelectorAll('.enemy-entry img')].every(i=>i.complete&&i.naturalWidth),null,{polling:100});assert.equal(await p.locator('.enemy-entry').count(),6);if(process.env.OUTPUT_DIR)await p.screenshot({path:process.env.OUTPUT_DIR+'/coast-v45-guide-'+width+'.png'});await p.getByRole('button',{name:'返回准备',exact:true}).click();await p.locator('[data-attack-mode=auto]').click();await p.locator('#start').click();await p.evaluate(()=>{const g=game3d;g.world.obstacles=[];g.world.patches=[];g.world.ponds=[];g.world.sites=[];g.player.inv=999;const e=g.spawn('reefturtle',g.player.x,g.player.z+2.5);e.hp=1000;e.speed=0;e.cool=999;for(let i=0;i<120;i++)g.step(1/60);if(e.hp>=1000)throw Error('auto thrust failed');});assert.deepEqual(errors,[]);console.log('PASS coast narrow thrust, pull, cancel, wall, tide/bridge/pause, lighthouse, boss, guide, auto',width,JSON.stringify(report));await p.close();
}}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
