const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{}),headless:true});try{
for(const [width,height] of [[1440,900],[844,390],[390,844]]){const p=await b.newPage({viewport:{width,height},hasTouch:width<1000}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:8897/');await p.waitForFunction(()=>window.game3d);await p.locator('#start').click();await p.waitForTimeout(300);
assert.equal(await p.evaluate(()=>game3d.audio.ctx.state),'running');assert(await p.locator('.xp').evaluate(e=>e.offsetHeight>=10));await p.evaluate(()=>{const p=game3d.player,e=game3d.spawn('mushroom',p.x+1,p.z+1);if(!e)throw Error('spawn failed');game3d.hurtEnemy(e,500);});await p.waitForTimeout(550);assert.equal(await p.evaluate(()=>game3d.player.xp),6);assert.equal(await p.locator('#xp-value').textContent(),'6 / 20');
const gain=await p.locator('#xp-gain').boundingBox(),hint=await p.locator('#hint').boundingBox();assert(gain.y+gain.height<=hint.y||hint.y+hint.height<=gain.y||gain.x+gain.width<=hint.x||hint.x+hint.width<=gain.x,'XP gain must not overlap hint');const box=await p.locator('.status').boundingBox();for(const selector of ['#pause','#sound','#audio-settings']){const r=await p.locator(selector).boundingBox();assert(box.y>=r.y+r.height||box.x+box.width<=r.x||box.y+box.height<=r.y,'HUD overlap: '+selector);}
await p.locator('#audio-settings summary').click();await p.locator('#music-volume').fill('41');await p.locator('#music-volume').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#music-volume').inputValue(),'42','keyboard must adjust slider');await p.locator('#sfx-volume').fill('73');await p.locator('#audio-settings summary').click();await p.locator('#sound').click();assert(await p.evaluate(()=>game3d.audio.muted));await p.locator('#pause').click();await p.getByRole('button',{name:'继续远征',exact:true}).click();assert(await p.evaluate(()=>game3d.audio.muted));await p.evaluate(()=>game3d.start());assert(await p.evaluate(()=>game3d.audio.muted));await p.reload();await p.waitForFunction(()=>window.game3d);assert.deepEqual(await p.evaluate(()=>[game3d.audio.musicVolume,game3d.audio.sfxVolume,game3d.audio.muted]),[.42,.73,true]);await p.locator('#start').click();await p.waitForTimeout(200);await p.locator('#sound').click();assert.equal(await p.evaluate(()=>game3d.audio.muted),false);
await p.evaluate(()=>game3d.grant(20));assert.equal(await p.evaluate(()=>game3d.state),'upgrade');await p.waitForTimeout(150);assert.equal(await p.locator('#xp-value').textContent(),'0 / 27');await p.locator('.cards button').first().click();assert.equal(await p.evaluate(()=>game3d.state),'playing');
await p.locator('#pause').click();assert.equal(await p.evaluate(()=>game3d.state),'paused');await p.waitForTimeout(1100);assert(await p.evaluate(()=>game3d.audio.music.gain.value<.01));assert.deepEqual(errors,[]);console.log(`PASS ${width}x${height}: XP pickup/level/bar, HUD layout, audio start, sliders, mute/pause/restart/persistence`);await p.close();}
const p=await b.newPage();await p.goto(process.env.TEST_URL||'http://127.0.0.1:8897/');const stats=await p.evaluate(async()=>{const {GameAudio}=await import('./audio.js?v=5');const out=[];for(const id of ['rifle','pistol','shotgun','fire','shuriken','dark','ice','storm','forest','snow','ash']){const music=['forest','snow','ash'].includes(id),seconds=music?3:1,c=new OfflineAudioContext(2,44100*seconds,44100),a=new GameAudio(c);a.muted=false;a.musicVolume=.65;a.sfxVolume=.8;a.setup();/* Schedule offline voices before rendering starts; real-time unlock is checked above. */a.available=()=>a.ready&&!a.muted&&a.nodes<100;if(music){a.reset(id);a.update(.016,{map:id,mode:'playing'});}else if(['ice','storm'].includes(id))a.spell(id);else a.shot(id);const rendered=await c.startRendering(),d=rendered.getChannelData(0);let sum=0,peak=0;for(const v of d){sum+=v*v;peak=Math.max(peak,Math.abs(v));}out.push({id,rms:Math.sqrt(sum/d.length),peak});}return out;});for(const r of stats){assert(r.rms>.001,`${r.id} must produce audible signal`);assert(r.peak<.98,`${r.id} clipping`);}console.log('PASS rendered weapon/spell signals and map opening chords:',JSON.stringify(stats));await p.close();
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});

