const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{
 for(const [width,height,touch]of [[1440,900,false],[844,390,true],[390,844,true]]){
  const p=await browser.newPage({viewport:{width,height},hasTouch:touch}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&/shader|THREE.WebGLProgram/.test(m.text()))errors.push(m.text());});
  await p.addInitScript(()=>{const raf=requestAnimationFrame;window.requestAnimationFrame=cb=>{window.nextFrame=cb;return raf(t=>{if(!window.freezeGame)cb(t)})}});
  await p.goto(process.env.TEST_URL||'http://127.0.0.1:8899/');await p.waitForFunction(()=>window.game3d,null,{polling:100,timeout:60000});await p.locator('#start').click();await p.evaluate(()=>freezeGame=true);await p.waitForTimeout(60);
  await p.evaluate(()=>{const g=game3d;g.world.obstacles.length=0;g.world.sites.length=0;g.world.patches=g.world.patches.filter(p=>p.kind==='swamp');const water=g.world.ponds[0];g.player.x=water.x;g.player.z=water.z;g.player.inv=999;});
  await p.keyboard.down('d');const speed=await p.evaluate(()=>{const g=game3d,x=g.player.x,z=g.player.z;for(let i=0;i<20;i++)g.step(1/60);return Math.hypot(g.player.x-x,g.player.z-z)/(20/60)});await p.keyboard.up('d');assert(Math.abs(speed-6.5*.48)<.02,'deep water speed');
  const result=await p.evaluate(()=>{const g=game3d;for(let i=0;i<30;i++)g.step(1/60);const wet={depth:g.player.waterDepth,blend:g.hero.userData.waterBlend,y:g.hero.userData.rig.position.y};g.pause();const time=g.time,y=g.hero.userData.rig.position.y;g.step(2);const paused=g.time===time&&g.hero.userData.rig.position.y===y;g.resume();const water=g.world.ponds[0];g.player.x=water.x+water.r+3;for(let i=0;i<80;i++)g.step(1/60);return{wet,paused,dry:{depth:g.player.waterDepth,blend:g.hero.userData.waterBlend}};});assert.equal(result.wet.depth,1);assert(result.wet.y<-.08&&result.wet.y>-.3);assert(result.paused);assert.equal(result.dry.depth,0);assert(result.dry.blend<.001);
  const poses=await p.evaluate(async()=>{const {animateActor}=await import('./world.js?v=38'),g=game3d,out=[];
   for(const hero of ['scout','silver','wraith']){g.select(hero,'forest',0);g.start();g.world.sites.length=0;g.world.obstacles.length=0;g.world.patches=g.world.patches.filter(p=>p.kind==='swamp');const water=g.world.ponds[0];g.player.x=water.x;g.player.z=water.z;g.player.inv=999;g.hero.rotation.y=g.player.angle=0;g.camera.position.set(water.x+17,24,water.z+17);g.camera.lookAt(water.x,.5,water.z);g.camera.updateMatrixWorld();
    for(let i=0;i<40;i++)g.step(1/60);g.dash();const from={x:g.player.x,z:g.player.z};for(let i=0;i<8;i++)g.step(1/60);out.push({hero,depth:g.player.waterDepth,roll:g.hero.userData.actions?.Roll.isRunning(),waterDash:g.hero.userData.waterDash});
    g.player.dashTime=0;g.player.attack=0;g.controls.angle=0;g.controls.hasAim=g.controls.held=true;for(let i=0;i<30&&!g.bullets.length;i++)g.step(1/60);if(!g.bullets.length)throw Error(hero+' cannot attack after water dodge');g.controls.held=false;
    g.hero.userData.waterDepth=1;for(let i=0;i<60;i++)animateActor(g.hero,g.time+i/60,3,0,0);g.hero.traverse(o=>{if(!Number.isFinite(o.quaternion.w))throw Error('invalid mud pose');});
   }return out;});assert.equal(poses[0].waterDash,true);assert.equal(poses[0].roll,false);assert.deepEqual(errors,[]);console.log('PASS water movement, pose, shore recovery, pause, three hero dodges and attacks',width,poses);await p.close();
 }
 // Visual review: render the real world and each hero close enough to inspect wading.
 const p=await browser.newPage({viewport:{width:1440,height:900}});await p.addInitScript(()=>{const raf=requestAnimationFrame;window.requestAnimationFrame=cb=>{window.nextFrame=cb;return raf(t=>{if(!window.freezeGame)cb(t)})}});await p.goto(process.env.TEST_URL||'http://127.0.0.1:8899/');await p.waitForFunction(()=>window.game3d);await p.locator('#start').click();await p.evaluate(()=>freezeGame=true);await p.waitForTimeout(60);
 const combat=await p.evaluate(()=>{const g=game3d,out=[];
  for(const hero of ['scout','silver','wraith'])for(let index=0;index<3;index++){
   g.select(hero,'forest',index);g.start();g.world.obstacles.length=0;g.world.sites.length=0;const water=g.world.ponds[0];g.world.patches=[water];g.player.x=water.x;g.player.z=water.z;g.player.inv=999;g.camera.position.set(water.x+17,24,water.z+17);g.camera.lookAt(water.x,.5,water.z);g.camera.updateMatrixWorld();
   const e=g.spawn('golem',water.x,water.z+3);e.hp=e.maxHp=1e5;e.cool=999;e.speed=0;g.controls.angle=0;g.controls.hasAim=g.controls.held=true;g.hero.rotation.y=0;g.step(1/60);g.controls.held=false;for(let i=0;i<60;i++)g.step(1/60);if(e.hp===e.maxHp)throw Error(g.player.weaponId+' cannot hit while wading');out.push(g.player.weaponId);
  }
  g.start();g.world.obstacles.length=0;g.world.sites.length=0;const pond=g.world.ponds[0];g.player.x=pond.x+12;g.player.z=pond.z;g.player.inv=999;
  const ratios={};for(const kind of ['wolf','golem','snowtotem']){const e=g.spawn(kind,pond.x,pond.z);e.cool=999;const distances=[];for(const wet of [false,true]){e.x=pond.x;e.z=pond.z;e.gait=0;g.world.patches=wet?[pond]:[];g.step(.016);distances.push(Math.hypot(e.x-pond.x,e.z-pond.z));}ratios[kind]=distances[1]/distances[0];e.alive=false;}
  return{weapons:out,ratios};});assert.equal(combat.weapons.length,9);assert(Math.abs(combat.ratios.wolf-.48)<.03);assert(Math.abs(combat.ratios.golem-.76)<.03);assert(Math.abs(combat.ratios.snowtotem-1)<.03);console.log('PASS nine weapons still hit in water, ground creature drag and hovering immunity',combat);
 for(const hero of ['silver','scout','wraith']){
  await p.evaluate(async hero=>{const {animateActor}=await import('./world.js?v=38'),g=game3d;g.select(hero,'forest',0);g.start();const pond=g.world.ponds[0];g.player.x=pond.x;g.player.z=pond.z;g.hero.position.set(pond.x,0,pond.z);g.hero.rotation.y=1;g.hero.userData.waterDepth=1;g.player.inv=999;g.pause();const draw=g.renderer.render.bind(g.renderer);let scene;g.renderer.render=(s,c)=>{scene=s;draw(s,c)};nextFrame(performance.now()+100);for(let i=0;i<60;i++)animateActor(g.hero,i/60,3,0,0);g.camera.position.set(pond.x+7,7,pond.z+8);g.camera.lookAt(pond.x,.2,pond.z);g.camera.updateMatrixWorld();g.renderer.render=draw;scene.updateMatrixWorld(true);g.hero.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.update();});draw(scene,g.camera);document.querySelector('#dialog').close();},hero);
  if(process.env.OUTPUT_DIR)await p.screenshot({path:process.env.OUTPUT_DIR+'/swamp-'+hero+'.png'});
 }await p.close();
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
