import test from 'node:test';import assert from 'node:assert/strict';
import{tideState,updateTide,harpoonHit,tideDashTravel}from'../coast.js';import{buildWorld,clearAt}from'../world.js';import{terrainAt,waterDepth}from'../water.js';import{createMapEvent,advanceMapEvent}from'../map-events.js';import{weaponStats,takeUpgrade,chooseUpgrades}from'../rules.js';import{recordVictory}from'../expedition.js';
globalThis.document={createElement:()=>({width:256,height:256,getContext:()=>({fillRect(){}})})};
test('coastal bridges cross the expanded water and retain clear entrances for 30 seeds',()=>{for(let seed=0;seed<30;seed++){const w=buildWorld('coast',seed);assert.equal(w.ponds.length,6);assert.equal(w.bridges.length,6);assert.equal(w.sites[0].event,'lighthouse');assert(clearAt(w,w.spawn.x,w.spawn.z,1));for(const s of w.sites)assert(clearAt(w,s.x,s.z,3));updateTide(w,21);for(const b of w.bridges){assert.equal(terrainAt(w,b.x,b.z).speed,1);for(const sign of[-1,1])assert(clearAt(w,b.x+sign*b.width/2,b.z,.5));}for(const o of w.group.children)if(o.isInstancedMesh)o.dispose();}});
test('tide warns before rising, expands visual and physical shores, and returns without drift',()=>{const w=buildWorld('coast',2),p=w.ponds[0],rx=p.rx;assert(!tideState(13).warning);assert(tideState(15).warning&&!tideState(15).high);for(let cycle=0;cycle<20;cycle++){updateTide(w,cycle*28+21);assert(p.rx>rx*1.18);assert.equal(p.mesh.scale.x,p.rx);updateTide(w,cycle*28+1);assert.equal(p.rx,rx);}w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose()});});
test('harpoon hits a narrow forward line, and both exclusive routes change their advertised properties',()=>{const o={x:0,z:0};assert(harpoonHit(o,{x:0,z:3},0,3.8,.48));assert(!harpoonHit(o,{x:1,z:2},0,3.8,.48));assert(!harpoonHit(o,{x:0,z:-1},0,3.8,.48));assert(!harpoonHit(o,{x:0,z:5},0,3.8,.48));for(const path of['harpoon_reef','harpoon_tow']){const p={heroId:'tide',weaponId:'harpoon',level:8,upgrades:{}},base=weaponStats(p);assert(!chooseUpgrades(p).some(s=>s.id==='fire'));for(let i=0;i<3;i++)assert(takeUpgrade(p,'path:'+path));const w=weaponStats(p);assert(w.damage>base.damage);assert(path==='harpoon_reef'?w.range>base.range:w.pull>base.pull&&w.slow>base.slow);assert(!takeUpgrade(p,'path:'+(path==='harpoon_reef'?'harpoon_tow':'harpoon_reef')));}});
test('lighthouse needs defeated guards and eight dry seconds, pauses and completes only once',()=>{const e=createMapEvent('lighthouse'),c={near:true,atCenter:true,guards:1,tide:tideState(1)};assert.equal(advanceMapEvent(e,.1,c).wave,1);advanceMapEvent(e,9,c);assert.equal(e.progress,0);c.guards=0;c.tide=tideState(15);advanceMapEvent(e,9,c);assert.equal(e.progress,0);c.tide=tideState(1);advanceMapEvent(e,3,c);assert.equal(e.progress,3);advanceMapEvent(e,20,{...c,near:false});assert.equal(e.progress,3);assert(advanceMapEvent(e,5,c).complete);assert(!advanceMapEvent(e,1,c).complete);});
test('tide dodge integrates to the same distance at all frame rates and new wins preserve old entries',()=>{for(const fps of[30,60,120]){let t=.3,d=0;while(t>0){const next=Math.max(0,t-1/fps);d+=tideDashTravel(next)-tideDashTravel(t);t=next;}assert(Math.abs(d-4.6)<1e-9);}const j={relics:[],wins:['forest:rifle']};assert(recordVictory(j,'coast','harpoon'));assert(recordVictory(j,'forest','harpoon'));assert.equal(j.wins[0],'forest:rifle');assert(!recordVictory(j,'coast','harpoon'));});

test('harbor water joins continuously and tide cannot flood reward centers',()=>{for(let seed=0;seed<12;seed++){const w=buildWorld('coast',seed);for(let z=-68;z<=68;z+=1)assert(w.ponds.some(p=>waterDepth(p,5,z)>0),'gap in waterway at '+z);updateTide(w,21);for(const s of w.sites)assert(w.ponds.every(p=>waterDepth(p,s.x,s.z)===0));w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose()});}});
