const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const p=await b.newPage();await p.goto(process.env.TEST_URL||'http://127.0.0.1:8899/',{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.game3d&&!document.querySelector('#start').disabled,null,{polling:200,timeout:60000});const frames=await p.evaluate(async()=>{
 const T=await import('./vendor/three.module.js'),{SkillVFX}=await import('./skill-vfx.js?v=62'),s=new T.Scene(),r=new T.WebGLRenderer({antialias:true});r.setSize(420,300);s.background=new T.Color(0x243c32);const floor=new T.Mesh(new T.PlaneGeometry(50,50),new T.MeshBasicMaterial({color:0x3e5546}));floor.rotation.x=-Math.PI/2;floor.position.y=-.01;s.add(floor);s.add(new T.GridHelper(50,50,0x486350,0x486350));const c=new T.PerspectiveCamera(38,1.4,.1,40);c.position.set(6,7.5,9);c.lookAt(0,.4,0);const v=new SkillVFX(s,{mobile:true}),out=[];
 const dummy=new T.Mesh(new T.CapsuleGeometry(.23,.65,4,8),new T.MeshBasicMaterial({color:0x344338}));dummy.position.set(.25,.58,0);s.add(dummy);
 for(const[name,cast]of[
 ['火焰爆发',()=>v.fire(0,0,3.5,true)],['冰霜破土',()=>v.ice(0,0,4)],['雷电分叉',()=>v.lightning(0,0,0,0,true)],['暗影撕裂',()=>{v.dark(0,0,2.8,true);v.riftCast(0,0,2.8,.65,true)}],
 ['蓄能岩脊',()=>v.skill({kind:'fault',x:0,z:0,angle:.5,charged:true})],['破浪锋',()=>v.skill({kind:'surge',x:0,z:0,angle:.5})],['藤缚合猎',()=>{v.skill({kind:'briar',x:0,z:0});v.skill({kind:'bond',x:0,z:0,linked:true})}],['箭雨',()=>v.skill({kind:'rain',x:0,z:0})]
 ])for(const age of[.04,.15,.32]){v.clear();cast();for(let t=0;t<age;t+=.01)v.update(.01);r.render(s,c);out.push({name:name+' '+age+' 秒',src:r.domElement.toDataURL()});}r.dispose();return out;
 });await p.setViewportSize({width:1260,height:900});await p.setContent('<style>body{margin:0;background:#243c32;color:#ead9ba;font:16px system-ui;display:grid;grid-template-columns:repeat(3,420px)}figure{margin:0;height:330px;text-align:center}img{width:420px;height:300px}</style>'+frames.map(v=>`<figure><img src="${v.src}"><figcaption>${v.name}</figcaption></figure>`).join(''));await p.screenshot({path:(process.env.OUTPUT_DIR||'.')+'/spell-effects-v62.png',fullPage:true});console.log('Rendered eight skill effects at three ages');}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
