import{MAP_HALF,mapPixel}from'../map-layout.js';
import{test}from'node:test';import assert from'node:assert/strict';import{buildWorld,clearAt,moveActor,actor,animateActor,animateWorld}from'../world.js';
globalThis.document={createElement:()=>({width:256,height:256,getContext:()=>({fillRect(){}})})};
test('90 generated maps keep spawn and exploration landmarks clear',()=>{for(const id of ['forest','snow','ash'])for(let seed=0;seed<30;seed++){const w=buildWorld(id,seed);assert(clearAt(w,w.spawn.x,w.spawn.z,1));for(const s of w.sites)assert(clearAt(w,s.x,s.z,3));w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});}});
test('solid trees and map bounds block movement',()=>{const w={obstacles:[{x:1,z:0,r:.65}]},p={x:0,z:0};moveActor(w,p,1,0,.45);assert.equal(p.x,0);assert(clearAt(w,70,0));for(const sign of [-1,1]){assert(!clearAt(w,sign*MAP_HALF,0));assert(!clearAt(w,0,sign*MAP_HALF));}assert.equal(mapPixel(-MAP_HALF),8);assert.equal(mapPixel(MAP_HALF),136);});
test('all models animate without invalid transforms',()=>{for(const id of ['silver','scout','mushroom','wolf','golem','spitter','shaman','boss']){const m=actor(id);animateActor(m,3,4,.1,0);m.traverse(o=>{assert(Number.isFinite(o.position.x));assert(Number.isFinite(o.scale.y));});}});
test('each map has animated local weather without additional draw calls per particle',()=>{for(const id of ['forest','snow','ash']){const w=buildWorld(id,42);assert.equal(w.weather.kind,id);assert(w.weather.mesh.isInstancedMesh);assert(w.weather.mesh.count>=30);animateWorld(w,0,w.spawn.x,w.spawn.z);const first=new w.weather.mesh.matrix.constructor();w.weather.mesh.getMatrixAt(0,first);animateWorld(w,2,w.spawn.x+4,w.spawn.z);const later=new w.weather.mesh.matrix.constructor();w.weather.mesh.getMatrixAt(0,later);assert.notDeepEqual([...first.elements],[...later.elements]);w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});}});
test('wolf tail swings while the merged mushroom spots follow the cap without rebuilding geometry',()=>{
 const wolf=actor('wolf');assert(wolf.userData.tail);animateActor(wolf,0,3,0,0);const first=wolf.userData.tail.rotation.y;animateActor(wolf,.2,3,0,0);assert.notEqual(wolf.userData.tail.rotation.y,first);
 const mushroom=actor('mushroom'),cap=mushroom.userData.cap,painted=cap.getObjectByName('mushroom-cap');assert(painted?.isMesh);assert.strictEqual(painted.parent,cap);assert.strictEqual(painted.geometry,actor('mushroom').userData.cap.getObjectByName('mushroom-cap').geometry);
 const colors=painted.geometry.attributes.color,swatches=new Set();for(let i=0;i<colors.count;i++)swatches.add([colors.getX(i),colors.getY(i),colors.getZ(i)].join(','));assert(swatches.size>=4,'cap, underside, gills and spots must retain their separate colors');
 const vertices=painted.geometry.attributes.position.array.slice();mushroom.updateMatrixWorld(true);const before=painted.matrixWorld.clone();animateActor(mushroom,0,3,0,0);animateActor(mushroom,.2,3,0,0);mushroom.updateMatrixWorld(true);assert(!painted.matrixWorld.equals(before),'cap stayed rigid during movement');assert(painted.matrixWorld.equals(cap.matrixWorld),'batched spots detached from the cap');assert.deepEqual(painted.geometry.attributes.position.array,vertices,'animation mutated shared cap geometry');
});
test('wolf and golem brace visibly before a strike',()=>{for(const kind of ['wolf','golem']){const m=actor(kind);animateActor(m,0,0,.6,0);animateActor(m,.2,0,.3,0);assert(m.userData.rig.position.y<-.055,`${kind} must lower its weight while winding up`);}});
test('a lunging wolf absorbs its landing instead of snapping to idle',()=>{const wolf=actor('wolf');wolf.userData.pounce=1;animateActor(wolf,0,0,0,0);wolf.userData.pounce=.08;animateActor(wolf,.18,0,0,0);wolf.userData.pounce=0;animateActor(wolf,.24,0,0,0);assert(wolf.userData.rig.position.y<-.035,'wolf landing has no compression');});
test('caster locomotion changes its silhouette instead of reusing idle sway',()=>{const idle=actor('spitter'),moving=actor('spitter');animateActor(idle,0,0,0,0);animateActor(moving,0,0,0,0);animateActor(idle,.25,0,0,0);animateActor(moving,.25,3,0,0);const a=idle.userData.rig.rotation,b=moving.userData.rig.rotation;assert(Math.hypot(b.x-a.x,b.z-a.z)>.025,'spitter movement looks the same as idle');});
test('ash vents keep their warning surface clear of stone pillars',()=>{for(let seed=0;seed<30;seed++){const w=buildWorld('ash',seed);for(const vent of w.patches.filter(p=>p.kind==='vent'))for(const pillar of w.obstacles)assert(Math.hypot(vent.x-pillar.x,vent.z-pillar.z)>=vent.r+pillar.r+.4);w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});}});
test('snow remains above the ground throughout a long run',()=>{const w=buildWorld('snow',7);const matrix=new w.weather.mesh.matrix.constructor();for(const t of [0,30,120,600]){animateWorld(w,t);for(let i=0;i<w.weather.mesh.count;i++){w.weather.mesh.getMatrixAt(i,matrix);assert(matrix.elements[13]>=.299&&matrix.elements[13]<4.301);}}w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});});
test('weather stays at world positions when the player moves and renews over time',()=>{for(const id of ['forest','snow','ash']){const w=buildWorld(id,11),matrix=new w.weather.mesh.matrix.constructor();animateWorld(w,0,w.spawn.x,w.spawn.z);w.weather.mesh.getMatrixAt(0,matrix);const before=[...matrix.elements],phases=w.weather.particles.map(p=>p.phase);animateWorld(w,0,w.spawn.x+4,w.spawn.z+4);w.weather.mesh.getMatrixAt(0,matrix);assert.deepEqual([...matrix.elements],before,`${id} particle followed the camera`);assert.equal(w.weather.mesh.position.x,0);assert.equal(w.weather.mesh.position.z,0);for(let frame=1;frame<=720;frame++)animateWorld(w,frame/60,w.spawn.x+4,w.spawn.z+4);w.weather.mesh.getMatrixAt(0,matrix);assert.notDeepEqual([...matrix.elements],before,`${id} particles never changed`);assert(w.weather.particles.some((p,i)=>p.phase!==phases[i]),`${id} particles never respawned`);w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});}});
test('restarting a map reuses its weather material',()=>{for(const id of ['forest','snow','ash']){const a=buildWorld(id,1),b=buildWorld(id,2);assert.strictEqual(a.weather.mesh.material,b.weather.mesh.material,`${id} created another GPU material`);for(const w of [a,b])w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});}});
test('fireflies have a shared soft core instead of opaque polygon faces',()=>{const a=buildWorld('forest',3),b=buildWorld('forest',4),material=a.weather.mesh.material,texture=material.map;assert.equal(a.weather.mesh.count,42);assert.equal(a.weather.mesh.geometry.type,'PlaneGeometry');assert.strictEqual(texture,b.weather.mesh.material.map);assert.equal(material.depthWrite,false);const {data,width}=texture.image;assert.equal(data[3],0);assert(data[((width/2)*width+width/2)*4+3]>200);for(const w of [a,b])w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});});

test('each expedition has five separated, seeded landmarks and a reachable early relic',()=>{const positions=new Set();for(let seed=1;seed<=30;seed++){const w=buildWorld('forest',seed),r=w.sites.find(s=>s.type==='relic');assert.equal(w.sites.length,5);assert(w.sites.slice(3).every(s=>Math.hypot(s.x,s.z)>65&&clearAt(w,s.x,s.z,3)));assert(Math.hypot(r.x-w.spawn.x,r.z-w.spawn.z)<33);for(const a of w.sites)for(const b of w.sites)if(a!==b)assert(Math.hypot(a.x-b.x,a.z-b.z)>15);positions.add(r.x+':'+r.z);w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose();});}assert.equal(positions.size,30);});

test('new map districts keep spawn, rewards and all bridge entrances reachable',()=>{for(const id of ['sand','coast'])for(let seed=0;seed<12;seed++){const w=buildWorld(id,seed);assert(w.districts.length>=1);assert(clearAt(w,w.spawn.x,w.spawn.z,1));for(const s of w.sites)assert(clearAt(w,s.x,s.z,3));const bound=w.half-2,size=bound+1,seen=new Set(),queue=[],cell=(x,z)=>[Math.round((x+bound)/2),Math.round((z+bound)/2)],start=cell(w.spawn.x,w.spawn.z);queue.push(start);seen.add(start.join(','));for(let i=0;i<queue.length;i++){const [x,z]=queue[i];for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,nz=z+dz,key=nx+','+nz;if(nx<0||nz<0||nx>=size||nz>=size||seen.has(key)||!clearAt(w,nx*2-bound,nz*2-bound,.5))continue;seen.add(key);queue.push([nx,nz]);}}for(const s of w.sites)assert(seen.has(cell(s.x,s.z).join(',')),id+' unreachable reward');for(const b of w.bridges||[])for(const side of[-1,1]){const x=b.x+Math.cos(b.angle||0)*(b.width/2+.6)*side,z=b.z-Math.sin(b.angle||0)*(b.width/2+.6)*side;assert(clearAt(w,x,z,.6),'blocked bridge entrance');assert(seen.has(cell(x,z).join(',')),'unreachable bridge entrance');}w.group.traverse(o=>{if(o.isInstancedMesh)o.dispose()});}});
